//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.Device.Ipvlan`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Ipvlan.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
  interface = "org.freedesktop.NetworkManager.Device.Ipvlan",
  assume_defaults = true
)]
pub trait Ipvlan {
  /// Mode property
  #[zbus(property)]
  fn mode(&self) -> zbus::Result<String>;

  /// Parent property
  #[zbus(property)]
  fn parent(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Private property
  #[zbus(property)]
  fn private(&self) -> zbus::Result<bool>;

  /// Vepa property
  #[zbus(property)]
  fn vepa(&self) -> zbus::Result<bool>;
}
