//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.Device.OvsBridge`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.OvsBridge.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
  interface = "org.freedesktop.NetworkManager.Device.OvsBridge",
  default_service = "org.freedesktop.NetworkManager"
)]
pub trait OvsBridge {
  /// Slaves property
  #[zbus(property)]
  fn slaves(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;
}
