#![allow(unused)]

// NetworkManager D-Bus API modules
mod access_point;
mod agent_manager;
mod checkpoint;
mod connection_active;
mod device;
mod device_adsl;
mod device_bluetooth;
mod device_bond;
mod device_bridge;
mod device_dummy;
mod device_generic;
mod device_hsr;
mod device_infiniband;
mod device_iptunnel;
mod device_ipvlan;
mod device_loopback;
mod device_lowpan;
mod device_macsec;
mod device_macvlan;
mod device_modem;
mod device_olpc_mesh;
mod device_ovs_bridge;
mod device_ovs_interface;
mod device_ovs_port;
mod device_ppp;
mod device_statistics;
mod device_team;
mod device_tun;
mod device_veth;
mod device_vlan;
mod device_vrf;
mod device_vxlan;
mod device_wi_max;
mod device_wifi_p2p;
mod device_wire_guard;
mod device_wired;
mod device_wireless;
mod device_wpan;
mod dhcp4_config;
mod dhcp6_config;
mod dns_manager;
mod ip4_config;
mod ip6_config;
mod network_manager;
mod ppp;
mod secret_agent;
mod settings;
mod settings_connection;
mod vpn_connection;
mod vpn_plugin;
mod wi_max_nsp;
mod wifi_p2p_peer;

// Re-export all items to make them available directly under networkmanager::api
pub use access_point::*;
pub use agent_manager::*;
pub use checkpoint::*;
pub use connection_active::*;
pub use device::*;
pub use device_adsl::*;
pub use device_bluetooth::*;
pub use device_bond::*;
pub use device_bridge::*;
pub use device_dummy::*;
pub use device_generic::*;
pub use device_hsr::*;
pub use device_infiniband::*;
pub use device_iptunnel::*;
pub use device_ipvlan::*;
pub use device_loopback::*;
pub use device_lowpan::*;
pub use device_macsec::*;
pub use device_macvlan::*;
pub use device_modem::*;
pub use device_olpc_mesh::*;
pub use device_ovs_bridge::*;
pub use device_ovs_interface::*;
pub use device_ovs_port::*;
pub use device_ppp::*;
pub use device_statistics::*;
pub use device_team::*;
pub use device_tun::*;
pub use device_veth::*;
pub use device_vlan::*;
pub use device_vrf::*;
pub use device_vxlan::*;
pub use device_wi_max::*;
pub use device_wifi_p2p::*;
pub use device_wire_guard::*;
pub use device_wired::*;
pub use device_wireless::*;
pub use device_wpan::*;
pub use dhcp4_config::*;
pub use dhcp6_config::*;
pub use dns_manager::*;
pub use ip4_config::*;
pub use ip6_config::*;
pub use network_manager::*;
pub use ppp::*;
pub use secret_agent::*;
pub use settings::*;
pub use settings_connection::*;
pub use vpn_connection::*;
pub use vpn_plugin::*;
pub use wi_max_nsp::*;
pub use wifi_p2p_peer::*;
