//! # D-Bus interface proxy for: `org.bluez.AdminPolicySet1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.AdminPolicySet1", default_service = "org.bluez")]
pub trait AdminPolicySet1 {
  /// Sets the service allowlist by specifying service UUIDs.
  ///
  /// When called, **bluetoothd(8)** will block incoming and outgoing connections to
  /// the service not in UUIDs for all of the clients.
  ///
  /// Any subsequent calls to this method will supersede any previously set allowlist
  /// values.  Calling this method with an empty array will allow any service UUIDs to
  /// be used.
  ///
  /// The default value is an empty array.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.Failed:
  fn set_service_allow_list(&self, uuids: &[String]) -> zbus::Result<()>;
}
