//! # D-Bus interface proxy for: `org.bluez.AdminPolicyStatus1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.AdminPolicyStatus1",
  default_service = "org.bluez"
)]
pub trait AdminPolicyStatus1 {
  /// Current value of service allow list.
  ///
  #[zbus(property)]
  fn service_allow_list(&self) -> zbus::Result<Vec<String>>;

  /// Indicate if there is any auto-connect profile in this device is not allowed by
  /// admin policy.
  #[zbus(property)]
  fn is_affected_by_policy(&self) -> zbus::Result<bool>;
}
