//! # D-Bus interface proxy for: `org.bluez.BatteryProviderManager1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.BatteryProviderManager1",
  default_service = "org.bluez"
)]
pub trait BatteryProviderManager1 {
  /// Registers a battery provider. A registered battery provider can then expose
  /// objects with **org.bluez.BatteryProvider(5)** interface.
  ///
  fn register_battery_provider(
    &self,
    provider: &zbus::zvariant::ObjectPath<'_>,
  ) -> zbus::Result<()>;

  /// Unregisters a battery provider previously registered with
  /// **RegisterBatteryProvider()**. After unregistration, the
  /// **org.bluez.BatteryProvider(5)** objects provided by this client are ignored by
  /// **bluetoothd(8)**.
  fn unregister_battery_provider(
    &self,
    provider: &zbus::zvariant::ObjectPath<'_>,
  ) -> zbus::Result<()>;
}
