//! # D-Bus interface proxy for: `org.bluez.BatteryProvider1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.BatteryProvider1",
  default_service = "org.bluez"
)]
pub trait BatteryProvider1 {
  /// The object path of the device that has this battery.
  #[zbus(property)]
  fn device(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;
}
