//! # D-Bus interface proxy for: `org.bluez.Battery1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.Battery1", default_service = "org.bluez")]
pub trait Battery1 {
  /// The percentage of battery left as an unsigned 8-bit integer.
  ///
  #[zbus(property)]
  fn percentage(&self) -> zbus::Result<u8>;

  /// Describes where the battery information comes from.
  ///
  /// This property is informational only and may be useful for debugging purposes.
  ///
  /// Providers from **org.bluez.BatteryProvider(5)** may make use of this property to
  /// indicate where the battery report comes from (e.g. "HFP 1.7", "HID", or the
  /// profile UUID).
  #[zbus(property)]
  fn source(&self) -> zbus::Result<String>;
}
