//! # D-Bus interface proxy for: `org.bluez.Bearer.LE1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.Bearer.LE1", default_service = "org.bluez")]
pub trait BearerLE1 {
  /// Connects all LE profiles the remote device supports that can be connected to and
  /// have been flagged as auto-connectable. If only subset of profiles is already
  /// connected it will try to connect currently disconnected ones.
  ///
  /// If at least one profile was connected successfully this method will indicate
  /// success.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.NotReady:
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.AlreadyConnected:
  ///
  fn connect(&self) -> zbus::Result<()>;

  /// Disconnects all connected profiles and then terminates low-level ACL-LE
  /// connection.
  ///
  /// ACL-LE connection will be terminated even if some profiles were not disconnected
  /// properly e.g. due to misbehaving device.
  ///
  /// This method can be also used to cancel a preceding Connect call before a reply
  /// to it has been received.
  ///
  /// For non-trusted devices connected calling this method will disable incoming
  /// connections until Connect method is called again.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.NotConnected:
  ///
  fn disconnect(&self) -> zbus::Result<()>;

  /// This signal is launched when a device is disconnected, with the reason of the
  /// disconnection.
  ///
  /// This could be used by client application, depending on internal policy, to try
  /// to reconnect to the device in case of timeout or unknown disconnection, or to
  /// try to connect to another device.
  ///
  /// Possible reasons:
  ///
  /// :org.bluez.Reason.Unknown:
  ///
  /// :org.bluez.Reason.Timeout:
  ///
  /// 	Connection timeout.
  ///
  /// 	The link supervision timeout has expired for a connection or the
  /// 	synchronization timeout has expired for a broadcast.
  ///
  /// :org.bluez.Reason.Local:
  ///
  /// 	Connection terminated by local host.
  ///
  /// 	The local device terminated the connection, terminated synchronization
  /// 	with a broadcaster, or terminated broadcasting packets.
  ///
  /// :org.bluez.Reason.Remote:
  ///
  /// 	Connection terminated by remote host.
  ///
  /// 	This disconnection can be due to:
  ///
  /// 	- the user on the remote device either terminated the connection or
  /// 	  stopped broadcasting packets,
  ///
  /// 	- the remote device terminated the connection because of low
  /// 	  resources,
  ///
  /// 	- the remote device terminated the connection because the device is
  /// 	  about to power off.
  ///
  /// :org.bluez.Reason.Authentication:
  ///
  /// 	Connection terminated due to an authentication failure.
  ///
  /// :org.bluez.Reason.Suspend:
  ///
  /// 	Connection terminated by local host for suspend.
  ///
  #[zbus(signal)]
  fn disconnected(&self, reason: String, message: String) -> zbus::Result<()>;

  /// The object path of the adapter the set belongs to.
  ///
  #[zbus(property)]
  fn adapter(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Indicates if the remote device is paired to LE bearer.
  ///
  /// Paired means the pairing process where devices exchange the information to
  /// establish an encrypted connection has been completed.
  ///
  #[zbus(property)]
  fn paired(&self) -> zbus::Result<bool>;

  /// Indicates if the remote device is bonded to LE bearer.
  ///
  /// Bonded means the information exchanged on pairing process has been stored and
  /// will be persisted.
  ///
  #[zbus(property)]
  fn bonded(&self) -> zbus::Result<bool>;

  /// Indicates if the remote device is currently connected to LE bearer.
  ///
  /// A PropertiesChanged signal indicate changes to this status.
  #[zbus(property)]
  fn connected(&self) -> zbus::Result<bool>;
}
