//! # D-Bus interface proxy for: `org.bluez.DeviceSet1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.DeviceSet1", default_service = "org.bluez")]
pub trait DeviceSet1 {
  /// Connects all **devices** members of the set, each member is connected in
  /// sequence as they were added/loaded following the same procedure as described in
  /// **Device1.Connect**.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.NotReady:
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.AlreadyConnected:
  ///
  fn connect(&self) -> zbus::Result<()>;

  /// Disconnects all **devices** members of the set, each member is disconnected in
  /// sequence as they were connected following the same procedure as described in
  /// **Device1.Disconnect**.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.NotConnected:
  ///
  fn disconnect(&self) -> zbus::Result<()>;

  /// The object path of the adapter the set belongs to.
  ///
  #[zbus(property)]
  fn adapter(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Indicates if the **devices** members of the set shall be automatically connected
  /// once any of its members is connected.
  ///
  #[zbus(property)]
  fn auto_connect(&self) -> zbus::Result<bool>;
  #[zbus(property)]
  fn set_auto_connect(&self, value: bool) -> zbus::Result<()>;

  /// List of devices objects that are members of the set.
  ///
  #[zbus(property)]
  fn devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

  /// Set members size.
  #[zbus(property)]
  fn size(&self) -> zbus::Result<u8>;
}
