//! # D-Bus interface proxy for: `org.bluez.Device1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.Device1", default_service = "org.bluez")]
pub trait Device1 {
  /// Connects all profiles the remote device supports that can be connected to and
  /// have been flagged as auto-connectable. If only subset of profiles is already
  /// connected it will try to connect currently disconnected ones.
  ///
  /// If at least one profile was connected successfully this method will indicate
  /// success.
  ///
  /// For dual-mode devices only one bearer is connected at time, the conditions are
  /// in the following order:
  ///
  /// 1. Connect the disconnected bearer if already connected.
  ///
  /// 2. Connect first the bonded bearer. If no bearers are bonded or both are skip
  ///    and check latest seen bearer.
  ///
  /// 3. Connect last used bearer, in case the timestamps are the same BR/EDR
  ///    takes precedence, or in case **PreferredBearer** has been set to a specific
  ///    bearer then that is used instead.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.NotReady:
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.AlreadyConnected:
  /// :org.bluez.Error.BREDR.ProfileUnavailable:
  ///
  fn connect(&self) -> zbus::Result<()>;

  /// Disconnects all connected profiles and then terminates low-level ACL connection.
  ///
  /// ACL connection will be terminated even if some profiles were not disconnected
  /// properly e.g. due to misbehaving device.
  ///
  /// This method can be also used to cancel a preceding Connect call before a reply
  /// to it has been received.
  ///
  /// For non-trusted devices connected over LE bearer calling this method will
  /// disable incoming connections until Connect method is called again.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.NotConnected:
  ///
  fn disconnect(&self) -> zbus::Result<()>;

  /// Connects a specific profile of this device. The UUID provided is the remote
  /// service UUID for the profile.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.NotAvailable:
  /// :org.bluez.Error.NotReady:
  ///
  fn connect_profile(&self, uuid: &str) -> zbus::Result<()>;

  /// Disconnects a specific profile of this device. The profile needs to be
  /// registered client profile.
  ///
  /// There is no connection tracking for a profile, so as long as the profile is
  /// registered this will always succeed.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.NotSupported:
  ///
  fn disconnect_profile(&self, uuid: &str) -> zbus::Result<()>;

  /// Connects to the remote device and initiate pairing procedure then proceed with
  /// service discovery.
  ///
  /// If the application has registered its own agent, then that specific agent will
  /// be used. Otherwise it will use the default agent.
  ///
  /// Only for applications like a pairing wizard it would make sense to have its own
  /// agent. In almost all other cases the default agent will handle this just fine.
  ///
  /// In case there is no application agent and also no default agent present, this
  /// method will fail.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.AlreadyExists:
  /// :org.bluez.Error.AuthenticationCanceled:
  /// :org.bluez.Error.AuthenticationFailed:
  /// :org.bluez.Error.AuthenticationRejected:
  /// :org.bluez.Error.AuthenticationTimeout:
  /// :org.bluez.Error.ConnectionAttemptFailed:
  ///
  fn pair(&self) -> zbus::Result<()>;

  /// Cancels a pairing operation initiated by the **Pair** method.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.DoesNotExist:
  /// :org.bluez.Error.Failed:
  ///
  fn cancel_pairing(&self) -> zbus::Result<()>;

  /// Returns all currently known BR/EDR service records for the device. Each
  /// individual byte array represents a raw SDP record, as defined by the Bluetooth
  /// Service Discovery Protocol specification.
  ///
  /// This method is intended to be only used by compatibility layers like Wine, that
  /// need to provide access to raw SDP records to support foreign Bluetooth APIs.
  ///
  /// General applications should instead use the Profile API for services-related
  /// functionality.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.NotReady:
  /// :org.bluez.Error.NotConnected:
  /// :org.bluez.Error.DoesNotExist:
  ///
  fn get_service_records(&self) -> zbus::Result<Vec<Vec<u8>>>;

  /// This signal is launched when a device is disconnected, with the reason of the
  /// disconnection.
  ///
  /// This could be used by client application, depending on internal policy, to try
  /// to reconnect to the device in case of timeout or unknown disconnection, or to
  /// try to connect to another device.
  ///
  /// Possible reasons:
  ///
  /// :org.bluez.Reason.Unknown:
  ///
  /// :org.bluez.Reason.Timeout:
  ///
  /// 	Connection timeout.
  ///
  /// 	The link supervision timeout has expired for a connection or the
  /// 	synchronization timeout has expired for a broadcast.
  ///
  /// :org.bluez.Reason.Local:
  ///
  /// 	Connection terminated by local host.
  ///
  /// 	The local device terminated the connection, terminated synchronization
  /// 	with a broadcaster, or terminated broadcasting packets.
  ///
  /// :org.bluez.Reason.Remote:
  ///
  /// 	Connection terminated by remote host.
  ///
  /// 	This disconnection can be due to:
  ///
  /// 	- the user on the remote device either terminated the connection or
  /// 	  stopped broadcasting packets,
  ///
  /// 	- the remote device terminated the connection because of low
  /// 	  resources,
  ///
  /// 	- the remote device terminated the connection because the device is
  /// 	  about to power off.
  ///
  /// :org.bluez.Reason.Authentication:
  ///
  /// 	Connection terminated due to an authentication failure.
  ///
  /// :org.bluez.Reason.Suspend:
  ///
  /// 	Connection terminated by local host for suspend.
  ///
  #[zbus(signal)]
  fn disconnected(&self, reason: String, message: String) -> zbus::Result<()>;

  /// The Bluetooth device address of the remote device.
  ///
  #[zbus(property)]
  fn address(&self) -> zbus::Result<String>;

  /// The Bluetooth device Address Type. For dual-mode and BR/EDR only devices this
  /// defaults to "public". Single mode LE devices may have either value.
  ///
  /// If remote device uses privacy than before pairing this represents address type
  /// used for connection and Identity Address after pairing.
  ///
  /// Possible values:
  ///
  /// :"public":
  ///
  /// 	Public address
  ///
  /// :"random":
  ///
  /// 	Random address
  ///
  #[zbus(property)]
  fn address_type(&self) -> zbus::Result<String>;

  /// The Bluetooth remote name.
  ///
  /// This value is only present for completeness. It is better to always use the
  /// **Alias** property when displaying the devices name.
  ///
  /// If the **Alias** property is unset, it will reflect this value which makes it
  /// more convenient.
  ///
  #[zbus(property)]
  fn name(&self) -> zbus::Result<String>;

  /// Proposed icon name according to the freedesktop.org icon naming specification.
  ///
  #[zbus(property)]
  fn icon(&self) -> zbus::Result<String>;

  /// The Bluetooth class of device of the remote device.
  ///
  #[zbus(property)]
  fn class(&self) -> zbus::Result<u32>;

  /// External appearance of device, as found on GAP service.
  ///
  #[zbus(property)]
  fn appearance(&self) -> zbus::Result<u16>;

  /// List of 128-bit UUIDs that represents the available remote services.
  ///
  #[zbus(property)]
  fn uuids(&self) -> zbus::Result<Vec<String>>;

  /// Indicates if the remote device is paired. Paired means the pairing process where
  /// devices exchange the information to establish an encrypted connection has been
  /// completed.
  ///
  #[zbus(property)]
  fn paired(&self) -> zbus::Result<bool>;

  /// Indicates if the remote device is bonded. Bonded means the information exchanged
  /// on pairing process has been stored and will be persisted.
  ///
  #[zbus(property)]
  fn bonded(&self) -> zbus::Result<bool>;

  /// Indicates if the remote device is currently connected.
  ///
  /// A PropertiesChanged signal indicate changes to this status.
  ///
  #[zbus(property)]
  fn connected(&self) -> zbus::Result<bool>;

  /// Indicates if the remote is seen as trusted.
  ///
  /// This setting can be changed by the application.
  ///
  #[zbus(property)]
  fn trusted(&self) -> zbus::Result<bool>;
  #[zbus(property)]
  fn set_trusted(&self, value: bool) -> zbus::Result<()>;

  /// If set to true any incoming connections from the device will be immediately
  /// rejected.
  ///
  /// Any device drivers will also be removed and no new ones will be probed as long
  /// as the device is blocked.
  ///
  #[zbus(property)]
  fn blocked(&self) -> zbus::Result<bool>;
  #[zbus(property)]
  fn set_blocked(&self, value: bool) -> zbus::Result<()>;

  /// If set to true this device will be allowed to wake the host from system suspend.
  ///
  #[zbus(property)]
  fn wake_allowed(&self) -> zbus::Result<bool>;
  #[zbus(property)]
  fn set_wake_allowed(&self, value: bool) -> zbus::Result<()>;

  /// The name alias for the remote device. The alias can be used to have a different
  /// friendly name for the remote device.
  ///
  /// In case no alias is set, it will return the remote device name. Setting an empty
  /// string as alias will convert it back to the remote device name.
  ///
  /// When resetting the alias with an empty string, the property will default back to
  /// the remote name.
  ///
  #[zbus(property)]
  fn alias(&self) -> zbus::Result<String>;
  #[zbus(property)]
  fn set_alias(&self, value: &str) -> zbus::Result<()>;

  /// The object path of the adapter the device belongs to.
  ///
  #[zbus(property)]
  fn adapter(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Set to true if the device only supports the pre-2.1 pairing mechanism.
  ///
  /// This property is useful during device discovery to anticipate whether legacy or
  /// simple pairing will occur if pairing is initiated.
  ///
  /// Note that this property can exhibit false-positives in the case of Bluetooth 2.1
  /// (or newer) devices that have disabled Extended Inquiry Response support.
  ///
  #[zbus(property)]
  fn legacy_pairing(&self) -> zbus::Result<bool>;

  /// Set to true if the device was cable paired and it doesn't support the canonical
  /// bonding with encryption, e.g. the Sixaxis gamepad.
  ///
  /// If true, BlueZ will establish a connection without enforcing encryption.
  ///
  #[zbus(property)]
  fn cable_pairing(&self) -> zbus::Result<bool>;

  /// Remote Device ID information in modalias format used by the kernel and udev.
  ///
  #[zbus(property)]
  fn modalias(&self) -> zbus::Result<String>;

  /// Received Signal Strength Indicator of the remote device (inquiry or
  /// advertising).
  ///
  #[zbus(property)]
  fn rssi(&self) -> zbus::Result<i16>;

  /// Advertised transmitted power level (inquiry or advertising).
  ///
  #[zbus(property)]
  fn tx_power(&self) -> zbus::Result<i16>;

  /// Manufacturer specific advertisement data. Keys are 16 bits Manufacturer ID
  /// followed by its byte array value.
  ///
  #[zbus(property)]
  fn manufacturer_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<u16, zbus::zvariant::OwnedValue>>;

  /// Service advertisement data. Keys are the UUIDs in string format followed by its
  /// byte array value.
  ///
  #[zbus(property)]
  fn service_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

  /// Indicate whether or not service discovery has been resolved.
  ///
  #[zbus(property)]
  fn services_resolved(&self) -> zbus::Result<bool>;

  /// The Advertising Data Flags of the remote device.
  ///
  #[zbus(property)]
  fn advertising_flags(&self) -> zbus::Result<Vec<u8>>;

  /// The Advertising Data of the remote device. Keys are 1 byte AD Type followed by
  /// data as byte array.
  ///
  /// Note: Only types considered safe to be handled by application are exposed.
  ///
  /// Possible values:
  ///
  /// :<type>:
  ///
  /// 	<byte array>
  ///
  /// Example:
  ///
  /// 	<Transport Discovery> <Organization Flags...>
  /// 	0x26                   0x01         0x01...
  ///
  #[zbus(property)]
  fn advertising_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<u8, zbus::zvariant::OwnedValue>>;

  /// The object paths of the sets the device belongs to followed by a dictionary
  /// which can contain the following:
  ///
  /// :byte Rank:
  ///
  /// 	Rank of the device in the Set.
  ///
  #[zbus(property)]
  fn sets(
    &self,
  ) -> zbus::Result<
    std::collections::HashMap<
      zbus::zvariant::OwnedObjectPath,
      std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
    >,
  >;

  /// Indicate the preferred bearer when initiating a connection, only available for
  /// dual-mode devices.
  ///
  /// When changing from "bredr" to "le" the device will be removed from the
  /// 'auto-connect' list so it won't automatically be connected when advertising.
  ///
  /// Note: Changes only take effect when the device is disconnected.
  ///
  /// Possible values:
  ///
  /// :"last-used":
  ///
  /// 	Connect to last used bearer first. Default.
  ///
  /// :"bredr":
  ///
  /// 	Connect to BR/EDR first.
  ///
  /// :"le":
  ///
  /// 	Connect to LE first.
  ///
  /// :"last-seen":
  ///
  /// 	Connect to last seen bearer first.
  #[zbus(property)]
  fn preferred_bearer(&self) -> zbus::Result<String>;
  #[zbus(property)]
  fn set_preferred_bearer(&self, value: &str) -> zbus::Result<()>;
}
