//! # D-Bus interface proxy for: `org.bluez.GattManager1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.GattManager1", default_service = "org.bluez")]
pub trait GattManager1 {
  /// Registers a local GATT services hierarchy as described above (GATT Server)
  /// and/or GATT profiles (GATT Client).
  ///
  /// The application object path together with the D-Bus system bus connection ID
  /// define the identification of the application registering a GATT based service
  /// (**org.bluez.GattService(5)**) and/or profile (**org.bluez.GattProfile(5)**).
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.AlreadyExists:
  ///
  fn register_application(
    &self,
    application: &zbus::zvariant::ObjectPath<'_>,
    options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;

  /// This unregisters the services and/or profiles that has been previously
  /// registered using **RegisterApplication()**. The object path parameter must match
  /// the same value that has been used on registration.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.DoesNotExist:
  fn unregister_application(
    &self,
    application: &zbus::zvariant::ObjectPath<'_>,
  ) -> zbus::Result<()>;
}
