//! # D-Bus interface proxy for: `org.bluez.GattProfile1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.GattProfile1", default_service = "org.bluez")]
pub trait GattProfile1 {
  /// This method gets called when **bluetoothd(8)** unregisters the profile. The
  /// profile can use it to do cleanup tasks.
  ///
  /// There is no need to unregister the profile, because when this method gets called
  /// it has already been unregistered.
  ///
  fn release(&self) -> zbus::Result<()>;

  /// 128-bit GATT service UUIDs to auto connect.
  #[zbus(property)]
  fn uuids(&self) -> zbus::Result<Vec<String>>;
}
