//! # D-Bus interface proxy for: `org.bluez.GattCharacteristic1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.GattCharacteristic1",
  default_service = "org.bluez"
)]
pub trait GattCharacteristic1 {
  /// Issues a request to read the value of the characteristic and returns the value
  /// if the operation was successful.
  ///
  /// Possible options:
  ///
  /// :uint16 offset:
  ///
  /// 	Read start offset in bytes.
  ///
  /// :uint16 mtu (server only):
  ///
  /// 	Exchange MTU in bytes.
  ///
  /// :object device (server only):
  ///
  /// 	Device object.
  ///
  /// :string link (server only):
  ///
  /// 	Link type.
  ///
  /// 	Possible values:
  ///
  /// 	:"BR/EDR":
  /// 	:"LE":
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  ///
  /// 	Possible values: string 0x80 - 0x9f
  ///
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.NotPermitted:
  /// :org.bluez.Error.NotAuthorized:
  /// :org.bluez.Error.InvalidOffset:
  /// :org.bluez.Error.NotSupported:
  ///
  fn read_value(
    &self,
    options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<Vec<u8>>;

  /// Issues a request to write the value of the characteristic.
  ///
  /// Possible options:
  ///
  /// :uint16 offset:
  ///
  /// 	Write start offset in bytes.
  ///
  /// :string type:
  ///
  /// 	Possible values:
  ///
  /// 	:"command":
  ///
  /// 		Use Write without response procedure.
  ///
  /// 	:"request":
  ///
  /// 		Use Write with response procedure.
  ///
  /// 	:"reliable":
  ///
  /// 		Use Reliable Write procedure.
  ///
  /// :uint16 mtu:
  ///
  /// 	Exchanged MTU (Server only).
  ///
  /// :object device:
  ///
  /// 	Device path (Server only).
  ///
  /// :string link:
  ///
  /// 	Link type (Server only).
  ///
  /// 	Possible values:
  ///
  /// 	:"BR/EDR":
  /// 	:"LE":
  ///
  /// :boolean prepare-authorize:
  ///
  /// 	True if prepare authorization request.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  ///
  /// 	Possible values: string 0x80 - 0x9f
  ///
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.NotPermitted:
  /// :org.bluez.Error.InvalidValueLength:
  /// :org.bluez.Error.NotAuthorized:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.ImproperlyConfigured:
  ///
  fn write_value(
    &self,
    value: &[u8],
    options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;

  /// Acquire file descriptor and MTU for writing. Only sockets are supported. Usage
  /// of WriteValue will be locked causing it to return NotPermitted error.
  ///
  /// For server the MTU returned shall be equal or smaller than the negotiated MTU.
  ///
  /// For client it only works with characteristic that has **WriteAcquired** property
  /// which relies on write-without-response **Flag**.
  ///
  /// To release the lock the client shall close the file descriptor, a HUP is
  /// generated in case the device is disconnected.
  ///
  /// Note: the MTU can only be negotiated once and is symmetric therefore this method
  /// may be delayed in order to have the exchange MTU completed, because of that the
  /// file descriptor is closed during reconnections as the MTU has to be
  /// renegotiated.
  ///
  /// Possible options:
  ///
  /// :object device:
  ///
  /// 	Object Device (Server only).
  ///
  /// :uint16 mtu:
  ///
  /// 	Exchanged MTU (Server only).
  ///
  /// :string link:
  ///
  /// 	Link type (Server only).
  ///
  /// 	Possible values:
  ///
  /// 	:"BR/EDR":
  /// 	:"LE":
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.NotSupported:
  ///
  fn acquire_write(
    &self,
    options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<(std::os::fd::RawFd, u16)>;

  /// Acquire file descriptor and MTU for notify. Only sockets are support.
  ///
  /// Usage of StartNotify will be locked causing it to return
  /// **org.bluez.Error.NotPermitted**.
  ///
  /// For server the MTU returned shall be equal or smaller than the negotiated MTU.
  ///
  /// Only works with characteristic that has **NotifyAcquired** property which relies
  /// on presence of **"notify" or "indicate"** **Flag** and no other client have
  /// called **StartNotify()**.
  ///
  /// Notification are enabled during this procedure so **StartNotify()** shall not be
  /// called, any notification will be dispatched via file descriptor therefore the
  /// Value property is not affected during the time where notify has been acquired.
  ///
  /// To release the lock the client shall close the file descriptor, a HUP is
  /// generated in case the device is disconnected.
  ///
  /// As a client if indication procedure is used the confirmation is generated
  /// automatically once received, for a server if the file descriptor is writable
  /// (POLLOUT) then upon receiving a confirmation from the client one byte (0x01) is
  /// written to the file descriptor.
  ///
  /// Note: the MTU can only be negotiated once and is symmetric therefore this method
  /// may be delayed in order to have the exchange MTU completed, because of that the
  /// file descriptor is closed during reconnections as the MTU has to be
  /// renegotiated.
  ///
  /// Possible options:
  ///
  /// :object device:
  ///
  /// 	Object Device (Server only).
  ///
  /// :uint16 mtu:
  ///
  /// 	Exchanged MTU (Server only).
  ///
  /// :string link:
  ///
  /// 	Link type (Server only).
  ///
  /// 	Possible values:
  ///
  /// 	:"BR/EDR":
  /// 	:"LE":
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.NotPermitted:
  ///
  fn acquire_notify(
    &self,
    options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<(std::os::fd::RawFd, u16)>;

  /// Starts a notification session from this characteristic if it supports value
  /// notifications or indications.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.NotPermitted:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.NotConnected:
  /// :org.bluez.Error.NotSupported:
  ///
  fn start_notify(&self) -> zbus::Result<()>;

  /// Stops or cancel session previously created by **StartNotify()**.
  ///
  /// Note that notifications from a characteristic are shared between sessions thus
  /// calling StopNotify will release a single session.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  ///
  fn stop_notify(&self) -> zbus::Result<()>;

  /// Confirms value was received.
  ///
  /// Possible Errors:
  ///
  /// org.bluez.Error.Failed
  ///
  fn confirm(&self) -> zbus::Result<()>;

  /// 128-bit characteristic UUID.
  ///
  #[zbus(property)]
  fn uuid(&self) -> zbus::Result<String>;

  /// Object path of the GATT service the characteristic belongs to.
  ///
  #[zbus(property)]
  fn service(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// The cached value of the characteristic. This property gets updated only after a
  /// successful read request and when a notification or indication is received, upon
  /// which a PropertiesChanged signal will be emitted.
  ///
  #[zbus(property)]
  fn value(&self) -> zbus::Result<Vec<u8>>;

  /// True, if this characteristic has been acquired by any client using AcquireWrite.
  ///
  /// For client properties is omitted in case 'write-without-response' flag is not
  /// set.
  ///
  /// For server the presence of this property indicates that AcquireWrite is
  /// supported.
  ///
  #[zbus(property)]
  fn write_acquired(&self) -> zbus::Result<bool>;

  /// True, if this characteristic has been acquired by any client using
  /// AcquireNotify.
  ///
  /// For client this properties is omitted in case 'notify' flag is not set.
  ///
  /// For server the presence of this property indicates that AcquireNotify is
  /// supported.
  ///
  #[zbus(property)]
  fn notify_acquired(&self) -> zbus::Result<bool>;

  /// True, if notifications or indications on this characteristic are currently
  /// enabled.
  ///
  #[zbus(property)]
  fn notifying(&self) -> zbus::Result<bool>;

  /// Defines how the characteristic value can be used. See Core spec
  /// "Table 3.5: Characteristic Properties bit field", and
  /// "Table 3.8: Characteristic Extended Properties bit field".
  ///
  /// The "x-notify" and "x-indicate" flags restrict access to notifications and
  /// indications by imposing write restrictions on a characteristic's client
  /// characteristic configuration descriptor.
  ///
  /// Possible values:
  ///
  /// :"broadcast":
  /// :"read":
  /// :"write-without-response":
  /// :"write":
  /// :"notify":
  /// :"indicate":
  /// :"authenticated-signed-writes":
  /// :"extended-properties":
  /// :"reliable-write":
  /// :"writable-auxiliaries":
  /// :"encrypt-read":
  /// :"encrypt-write":
  /// :"encrypt-notify" (Server only):
  /// :"encrypt-indicate" (Server only):
  /// :"encrypt-authenticated-read":
  /// :"encrypt-authenticated-write":
  /// :"encrypt-authenticated-notify" (Server only):
  /// :"encrypt-authenticated-indicate" (Server only):
  /// :"secure-read" (Server only):
  /// :"secure-write" (Server only):
  /// :"secure-notify" (Server only):
  /// :"secure-indicate" (Server only):
  /// :"authorize":
  ///
  #[zbus(property)]
  fn flags(&self) -> zbus::Result<Vec<String>>;

  /// Characteristic handle. When available in the server it would attempt to use to
  /// Characteristic handle.
  ///
  /// Characteristic handle. When available in the server it would attempt to use to
  /// allocate into the database which may fail, to auto allocate the value 0x0000
  /// shall be used which will cause the allocated handle to be set once registered.
  ///
  #[zbus(property)]
  fn handle(&self) -> zbus::Result<u16>;

  /// Characteristic MTU, this is valid both for **ReadValue()** and **WriteValue()**
  /// but either method can use long procedures when supported.
  #[zbus(property)]
  fn mtu(&self) -> zbus::Result<u16>;
}
