//! # D-Bus interface proxy for: `org.bluez.GattService1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.GattService1", default_service = "org.bluez")]
pub trait GattService1 {
  /// 128-bit service UUID.
  ///
  #[zbus(property)]
  fn uuid(&self) -> zbus::Result<String>;

  /// Indicates whether or not this GATT service is a primary service. If false, the
  /// service is secondary.
  ///
  #[zbus(property)]
  fn primary(&self) -> zbus::Result<bool>;

  /// Object path of the Bluetooth device the service belongs to. Only present on
  /// services from remote devices.
  ///
  #[zbus(property)]
  fn device(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Array of object paths representing the included services of this service.
  ///
  #[zbus(property)]
  fn includes(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

  /// Service handle. When available in the server it would attempt to use to allocate
  /// Service handle.
  ///
  /// Service handle. When available in the server it would attempt to use to allocate
  /// into the database which may fail, to auto allocate the value 0x0000 shall be
  /// used which will cause the allocated handle to be set once registered.
  #[zbus(property)]
  fn handle(&self) -> zbus::Result<u16>;
}
