//! # D-Bus interface proxy for: `org.bluez.GattDescriptor1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.GattDescriptor1", default_service = "org.bluez")]
pub trait GattDescriptor1 {
  /// Issues a request to read the value of the descriptor and returns the value if
  /// the operation was successful.
  ///
  /// Possible options:
  ///
  /// :uint16 offset:
  ///
  /// 	Read start offset in bytes.
  ///
  /// :object device (server only):
  ///
  /// 	Device object.
  ///
  /// :string link:
  ///
  /// 	Link type (Server only).
  ///
  /// 	Possible values:
  ///
  /// 	:"BR/EDR":
  /// 	:"LE":
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.NotPermitted:
  /// :org.bluez.Error.NotAuthorized:
  /// :org.bluez.Error.NotSupported:
  ///
  fn read_value(
    &self,
    flags: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<Vec<u8>>;

  /// Issues a request to write the value of the descriptor.
  ///
  /// Possible flags:
  ///
  /// :uint16 offset:
  ///
  /// 	Write start offset in bytes.
  ///
  /// :uint16 mtu:
  ///
  /// 	Exchanged MTU (Server only).
  ///
  /// :object device:
  ///
  /// 	Device path (Server only).
  ///
  /// :string link:
  ///
  /// 	Link type (Server only).
  ///
  /// 	Possible values:
  ///
  /// 	:"BR/EDR":
  /// 	:"LE":
  ///
  /// :boolean prepare-authorize:
  ///
  /// 	True if prepare authorization request.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.NotPermitted:
  /// :org.bluez.Error.InvalidValueLength:
  /// :org.bluez.Error.NotAuthorized:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.ImproperlyConfigured:
  ///
  fn write_value(
    &self,
    value: &[u8],
    flags: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;

  /// 128-bit descriptor UUID.
  ///
  #[zbus(property)]
  fn uuid(&self) -> zbus::Result<String>;

  /// Object path of the GATT characteristic the descriptor belongs to.
  ///
  #[zbus(property)]
  fn characteristic(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// The cached value of the descriptor. This property gets updated only after a
  /// successful read request, upon which a PropertiesChanged signal will be emitted.
  ///
  #[zbus(property)]
  fn value(&self) -> zbus::Result<Vec<u8>>;

  /// Defines how the descriptor value can be used.
  ///
  /// Possible values:
  ///
  /// :"read":
  /// :"write":
  /// :"encrypt-read":
  /// :"encrypt-write":
  /// :"encrypt-authenticated-read":
  /// :"encrypt-authenticated-write":
  /// :"secure-read" (Server Only):
  /// :"secure-write" (Server Only):
  /// :"authorize":
  ///
  #[zbus(property)]
  fn flags(&self) -> zbus::Result<Vec<String>>;

  /// Descriptor handle. When available in the server it would attempt to use to
  /// Descriptor handle.
  ///
  /// Descriptor handle. When available in the server it would attempt to use to
  /// allocate into the database which may fail, to auto allocate the value 0x0000
  /// shall be used which will cause the allocated handle to be set once registered.
  #[zbus(property)]
  fn handle(&self) -> zbus::Result<u16>;
}
