//! # D-Bus interface proxy for: `org.bluez.HealthChannel1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.HealthChannel1", default_service = "org.bluez")]
pub trait HealthChannel1 {
  /// Returns the file descriptor for this data channel. If
  /// the data channel is not connected it will also
  /// reconnect.
  ///
  /// Possible Errors: org.bluez.Error.NotConnected
  ///          org.bluez.Error.NotAllowed
  ///
  fn acquire(&self) -> zbus::Result<std::os::fd::RawFd>;

  /// Releases the fd. Application should also need to
  /// close() it.
  ///
  /// Possible Errors: org.bluez.Error.NotAcquired
  ///          org.bluez.Error.NotAllowed
  ///
  fn release(&self) -> zbus::Result<()>;

  /// The quality of service of the data channel. ("reliable"
  /// or "streaming")
  ///
  #[zbus(property)]
  fn type_(&self) -> zbus::Result<String>;

  /// Identifies the Remote Device that is connected with.
  /// Maps with a HealthDevice object.
  ///
  #[zbus(property)]
  fn device(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Identifies the HealthApplication to which this channel
  /// is related to (which indirectly defines its role and
  /// data type).
  #[zbus(property)]
  fn application(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;
}
