//! # D-Bus interface proxy for: `org.bluez.HealthManager1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.HealthManager1", default_service = "org.bluez")]
pub trait HealthManager1 {
  /// Returns the path of the new registered application.
  /// Application will be closed by the call or implicitly
  /// when the programs leaves the bus.
  ///
  /// config:
  ///     uint16 DataType:
  ///
  ///         Mandatory
  ///
  ///     string Role:
  ///
  ///         Mandatory. Possible values: "source",
  ///                         "sink"
  ///
  ///     string Description:
  ///
  ///         Optional
  ///
  ///     ChannelType:
  ///
  ///         Optional, just for sources. Possible
  ///         values: "reliable", "streaming"
  ///
  /// Possible Errors: org.bluez.Error.InvalidArguments
  ///
  fn create_application(
    &self,
    config: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Closes the HDP application identified by the object
  /// path. Also application will be closed if the process
  /// that started it leaves the bus. Only the creator of the
  /// application will be able to destroy it.
  ///
  /// Possible errors: org.bluez.Error.InvalidArguments
  ///          org.bluez.Error.NotFound
  ///          org.bluez.Error.NotAllowed
  ///
  fn destroy_application(&self, application: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;
}
