//! # D-Bus interface proxy for: `org.bluez.HealthDevice1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.HealthDevice1", default_service = "org.bluez")]
pub trait HealthDevice1 {
  /// Sends an echo petition to the remote service. Returns
  /// True if response matches with the buffer sent. If some
  /// error is detected False value is returned.
  ///
  /// Possible errors: org.bluez.Error.InvalidArguments
  ///          org.bluez.Error.OutOfRange
  ///
  fn echo(&self) -> zbus::Result<bool>;

  /// Creates a new data channel.  The configuration should
  /// indicate the channel quality of service using one of
  /// this values "reliable", "streaming", "any".
  ///
  /// Returns the object path that identifies the data
  /// channel that is already connected.
  ///
  /// Possible errors: org.bluez.Error.InvalidArguments
  ///          org.bluez.Error.HealthError
  ///
  fn create_channel(
    &self,
    application: &zbus::zvariant::ObjectPath<'_>,
    configuration: &str,
  ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Destroys the data channel object. Only the creator of
  /// the channel or the creator of the HealthApplication
  /// that received the data channel will be able to destroy
  /// it.
  ///
  /// Possible errors: org.bluez.Error.InvalidArguments
  ///          org.bluez.Error.NotFound
  ///              org.bluez.Error.NotAllowed
  ///
  fn destroy_channel(&self, channel: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

  /// This signal is launched when a new data channel is
  /// created or when a known data channel is reconnected.
  ///
  #[zbus(signal)]
  fn channel_connected(&self, channel: zbus::zvariant::OwnedObjectPath) -> zbus::Result<()>;

  /// This signal is launched when a data channel is deleted.
  ///
  /// After this signal the data channel path will not be
  /// valid and its path can be reused for future data
  /// channels.
  ///
  #[zbus(signal)]
  fn channel_deleted(&self, channel: zbus::zvariant::OwnedObjectPath) -> zbus::Result<()>;

  /// The first reliable channel opened. It is needed by
  /// upper applications in order to send specific protocol
  /// data units. The first reliable can change after a
  /// reconnection.
  ///
  #[zbus(property)]
  fn main_channel(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;
}
