//! # D-Bus interface proxy for: `org.bluez.LEAdvertisement1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.LEAdvertisement1",
  default_service = "org.bluez"
)]
pub trait LEAdvertisement1 {
  /// This method gets called when the **bluetoothd(8)** removes the Advertisement.
  ///
  /// A client can use it to do cleanup tasks. There is no need to call
  /// **UnregisterAdvertisement()** because when this method gets called it has
  /// already been unregistered.
  ///
  fn release(&self) -> zbus::Result<()>;

  /// Determines the type of advertising packet requested.
  ///
  /// Possible values:
  ///
  /// :"broadcast":
  /// :"peripheral":
  ///
  #[zbus(property)]
  fn type_(&self) -> zbus::Result<String>;

  /// List of UUIDs to include in the "Service UUID" field of the Advertising Data.
  ///
  #[zbus(property)]
  fn service_uuids(&self) -> zbus::Result<Vec<String>>;

  /// Manufacturer Data fields to include in the Advertising Data.
  ///
  /// Keys are the Manufacturer ID to associate with the data.
  ///
  #[zbus(property)]
  fn manufacturer_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<u16, zbus::zvariant::OwnedValue>>;

  /// List of UUIDs to include in the "Service Solicitation" field of the Advertising
  /// Data.
  ///
  #[zbus(property)]
  fn solicit_uuids(&self) -> zbus::Result<Vec<String>>;

  /// Service Data elements to include in the Advertising Data.
  ///
  /// The keys are the UUID to associate with the data.
  ///
  #[zbus(property)]
  fn service_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

  /// Advertising Data to include.
  ///
  /// Key is the advertising type and value is the data as byte array.
  ///
  /// Note: Types already handled by other properties shall not be used.
  ///
  /// Possible values:
  ///
  /// :<type>:
  ///
  /// 	<byte array>
  ///
  /// Example:
  /// 	<Transport Discovery> <Organization Flags...>
  /// 	0x26                   0x01         0x01...
  ///
  #[zbus(property)]
  fn data(&self) -> zbus::Result<std::collections::HashMap<u8, zbus::zvariant::OwnedValue>>;

  /// List of UUIDs to include in the "Service UUID" field of the Scan Response Data.
  ///
  #[zbus(property)]
  fn scan_response_service_uuids(&self) -> zbus::Result<Vec<String>>;

  /// Manufacturer Data fields to include in the Scan Response Data.
  ///
  /// Keys are the Manufacturer ID to associate with the data.
  ///
  #[zbus(property)]
  fn scan_response_manufacturer_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<u16, zbus::zvariant::OwnedValue>>;

  /// List of UUIDs to include in the "Service Solicitation" field of the Scan
  /// Response Data.
  ///
  #[zbus(property)]
  fn scan_response_solicit_uuids(&self) -> zbus::Result<Vec<String>>;

  /// Service Data elements to include in the Scan Response Data.
  ///
  /// The keys are the UUID to associate with the data.
  ///
  #[zbus(property)]
  fn scan_response_service_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

  /// Scan Response Data to include.
  ///
  /// Key is the advertising type and value is the data as byte array.
  ///
  #[zbus(property)]
  fn scan_response_data(
    &self,
  ) -> zbus::Result<std::collections::HashMap<u8, zbus::zvariant::OwnedValue>>;

  /// Advertise as general discoverable. When present this will override adapter
  /// Discoverable property.
  ///
  /// Note: This property shall not be set when **Type** is set to "broadcast".
  ///
  #[zbus(property)]
  fn discoverable(&self) -> zbus::Result<bool>;

  /// The discoverable timeout in seconds. A value of zero means that the timeout is
  /// disabled and it will stay in discoverable/limited mode forever.
  ///
  /// Note: This property shall not be set when **Type** is set to "broadcast".
  ///
  #[zbus(property)]
  fn discoverable_timeout(&self) -> zbus::Result<u16>;

  /// List of features to be included in the advertising packet.
  ///
  /// Possible values:
  ///
  /// See **org.bluez.LEAdvertisingManager(5)** **SupportedIncludes** property.
  ///
  #[zbus(property)]
  fn includes(&self) -> zbus::Result<Vec<String>>;

  /// Local name to be used in the advertising report. If the string is too big to
  /// fit into the packet it will be truncated.
  ///
  /// If this property is available 'local-name' cannot be present in the
  /// **Includes**.
  ///
  #[zbus(property)]
  fn local_name(&self) -> zbus::Result<String>;

  /// Appearance to be used in the advertising report.
  ///
  /// Possible values: as found on GAP Service.
  ///
  #[zbus(property)]
  fn appearance(&self) -> zbus::Result<u16>;

  /// Rotation duration of the advertisement in seconds.
  ///
  /// If there are other applications advertising no duration is set the default is
  /// 2 seconds.
  ///
  #[zbus(property)]
  fn duration(&self) -> zbus::Result<u16>;

  /// Timeout of the advertisement in seconds. This defines the lifetime of the
  /// advertisement.
  ///
  #[zbus(property)]
  fn timeout(&self) -> zbus::Result<u16>;

  /// Secondary channel to be used.
  ///
  /// Primary channel is always set to "1M" except when "Coded" is set.
  ///
  /// Possible value:
  ///
  /// :"1M" (default):
  /// :"2M":
  /// :"Coded":
  ///
  #[zbus(property)]
  fn secondary_channel(&self) -> zbus::Result<String>;

  /// Minimum advertising interval to be used by the advertising set, in milliseconds.
  ///
  /// Acceptable values are in the range [20ms, 10,485s].
  ///
  /// If the provided MinInterval is larger than the provided MaxInterval, the
  /// registration will return failure.
  ///
  #[zbus(property)]
  fn min_interval(&self) -> zbus::Result<u32>;

  /// Maximum advertising interval to be used by the advertising set, in milliseconds.
  ///
  /// Acceptable values are in the range [20ms, 10,485s].
  ///
  /// If the provided MinInterval is larger than the provided MaxInterval, the
  /// registration will return failure.
  ///
  #[zbus(property)]
  fn max_interval(&self) -> zbus::Result<u32>;

  /// Requested transmission power of this advertising set.
  ///
  /// The provided value is used only if the "CanSetTxPower" feature is enabled on the
  /// **org.bluez.LEAdvertisingManager(5)**.
  ///
  /// Values must be in range [-127 to +20], where units are in dBm.
  #[zbus(property)]
  fn tx_power(&self) -> zbus::Result<i16>;
}
