//! # D-Bus interface proxy for: `org.bluez.LEAdvertisingManager1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.LEAdvertisingManager1",
  default_service = "org.bluez"
)]
pub trait LEAdvertisingManager1 {
  /// Registers an advertisement object to be sent over the LE Advertising channel.
  ///
  /// The service must implement **org.bluez.LEAdvertisement(5)** interface.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  ///
  /// 	Indicates that the object has invalid or conflicting properties.
  ///
  /// :org.bluez.Error.AlreadyExists:
  ///
  /// 	Indicates the object is already registered.
  ///
  /// :org.bluez.Error.InvalidLength:
  ///
  /// 	Indicates that the data provided generates a data packet which is too
  /// 	long.
  ///
  /// :org.bluez.Error.NotPermitted:
  ///
  /// 	Indicates the maximum number of advertisement instances has been
  /// 	reached.
  ///
  fn register_advertisement(
    &self,
    advertisement: &zbus::zvariant::ObjectPath<'_>,
    options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;

  /// Unregisters an advertisement that has been previously registered using
  /// **RegisterAdvertisement()**.
  ///
  /// The object path parameter must match the same value that has been used on
  /// registration.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.DoesNotExist:
  ///
  fn unregister_advertisement(
    &self,
    advertisement: &zbus::zvariant::ObjectPath<'_>,
  ) -> zbus::Result<()>;

  /// Number of active advertising instances.
  ///
  #[zbus(property)]
  fn active_instances(&self) -> zbus::Result<u8>;

  /// Number of available advertising instances.
  ///
  #[zbus(property)]
  fn supported_instances(&self) -> zbus::Result<u8>;

  /// List of supported system includes.
  ///
  /// Possible values:
  ///
  /// :"tx-power":
  /// :"appearance":
  /// :"local-name":
  /// :"rsi":
  ///
  #[zbus(property)]
  fn supported_includes(&self) -> zbus::Result<Vec<String>>;

  /// List of supported Secondary channels. Secondary channels can be used to
  /// advertise with the corresponding PHY.
  ///
  /// Possible values:
  ///
  /// :"1M":
  /// :"2M":
  /// :"Coded":
  ///
  #[zbus(property)]
  fn supported_secondary_channels(&self) -> zbus::Result<Vec<String>>;

  /// Enumerates Advertising-related controller capabilities useful to the client.
  ///
  /// Possible Values:
  ///
  /// :byte MaxAdvLen:
  ///
  /// 	Max advertising data length
  ///
  /// :byte MaxScnRspLen:
  ///
  /// 	Max advertising scan response length
  ///
  /// :int16 MinTxPower:
  ///
  /// 	Min advertising tx power (dBm)
  ///
  /// :int16 MaxTxPower:
  ///
  /// 	Max advertising tx power (dBm)
  ///
  #[zbus(property)]
  fn supported_capabilities(
    &self,
  ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

  /// List of supported platform features. If no features are available on the
  /// platform, the SupportedFeatures array will be empty.
  ///
  /// Possible values:
  ///
  /// :"CanSetTxPower":
  ///
  /// 	Indicates whether platform can specify tx power on each advertising
  /// 	instance.
  ///
  /// :"HardwareOffload":
  ///
  /// 	Indicates whether multiple advertising will be offloaded to the
  /// 	controller.
  #[zbus(property)]
  fn supported_features(&self) -> zbus::Result<Vec<String>>;
}
