//! # D-Bus interface proxy for: `org.bluez.MediaControl1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.MediaControl1", default_service = "org.bluez")]
pub trait MediaControl1 {
  /// Resume playback.
  ///
  fn play(&self) -> zbus::Result<()>;

  /// Pause playback.
  ///
  fn pause(&self) -> zbus::Result<()>;

  /// Stop playback.
  ///
  fn stop(&self) -> zbus::Result<()>;

  /// Next item.
  ///
  fn next(&self) -> zbus::Result<()>;

  /// Previous item.
  ///
  fn previous(&self) -> zbus::Result<()>;

  /// Adjust remote volume one step up
  ///
  fn volume_up(&self) -> zbus::Result<()>;

  /// Adjust remote volume one step down
  ///
  fn volume_down(&self) -> zbus::Result<()>;

  /// Fast forward playback, this action is only stopped when another method in this
  /// interface is called.
  ///
  fn fast_forward(&self) -> zbus::Result<()>;

  /// Rewind playback, this action is only stopped when another method in this
  /// interface is called.
  ///
  fn rewind(&self) -> zbus::Result<()>;

  #[zbus(property)]
  fn connected(&self) -> zbus::Result<bool>;

  /// Addressed Player object path.
  #[zbus(property)]
  fn player(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;
}
