//! # D-Bus interface proxy for: `org.bluez.MediaAssistant1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.MediaAssistant1", default_service = "org.bluez")]
pub trait MediaAssistant1 {
  /// Send stream information to the remote device.
  ///
  /// :dict properties:
  ///
  /// Indicate stream properties that will be sent to the peer.
  ///
  /// Values:
  ///
  /// 	:array{byte} Metadata [ISO only]:
  ///
  /// 		See Metadata property.
  ///
  /// 	:dict QoS [ISO only]:
  ///
  /// 		See QoS property.
  ///
  /// 	:object Device [ISO only, State=local only]:
  ///
  /// 		Push to a specific device. Device must be connected and with
  /// 		an active BASS session.
  ///
  fn push(
    &self,
    properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;

  /// Indicates the state of the assistant object. Possible values are:
  ///
  /// :"idle": assistant object was created for the stream
  /// :"pending": assistant object was pushed (stream information was sent to the peer)
  /// :"requesting": remote device requires Broadcast_Code
  /// :"active": remote device started receiving stream
  /// :"local": assistant object was created for a local stream
  ///
  #[zbus(property)]
  fn state(&self) -> zbus::Result<String>;

  /// Indicates stream Metadata.
  ///
  #[zbus(property)]
  fn metadata(&self) -> zbus::Result<Vec<u8>>;
  #[zbus(property)]
  fn set_metadata(&self, value: &[u8]) -> zbus::Result<()>;

  /// Indicates stream QoS capabilities.
  ///
  /// Values:
  ///
  /// :byte Encryption:
  ///
  /// 	Indicates whether the stream is encrypted.
  ///
  /// :array{byte} BCode
  ///
  /// 	Indicates Broadcast_Code to decrypt stream.
  #[zbus(property)]
  fn qo_s(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
  #[zbus(property)]
  fn set_qo_s(
    &self,
    value: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;
}
