//! # D-Bus interface proxy for: `org.bluez.MediaItem1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.MediaItem1", default_service = "org.bluez")]
pub trait MediaItem1 {
  /// Play item
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn play(&self) -> zbus::Result<()>;

  /// Add item to now playing list
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn addto_now_playing(&self) -> zbus::Result<()>;

  /// Player object path the item belongs to
  ///
  #[zbus(property)]
  fn player(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Item displayable name
  ///
  #[zbus(property)]
  fn name(&self) -> zbus::Result<String>;

  /// Item type
  ///
  /// Possible values:
  ///
  /// :"video":
  /// :"audio":
  /// :"folder":
  ///
  #[zbus(property)]
  fn type_(&self) -> zbus::Result<String>;

  /// Folder type.
  ///
  /// Available if property Type is "Folder"
  ///
  /// Possible values:
  ///
  /// :"mixed":
  /// :"titles":
  /// :"albums":
  /// :"artists":
  ///
  #[zbus(property)]
  fn folder_type(&self) -> zbus::Result<String>;

  /// Indicates if the item can be played
  ///
  /// Available if property Type is "folder"
  ///
  #[zbus(property)]
  fn playable(&self) -> zbus::Result<bool>;

  /// Item metadata.
  ///
  /// Possible values:
  ///
  /// :string Title:
  ///
  /// 	Item title name
  ///
  /// 	Available if property Type is "audio" or "video"
  ///
  /// :string Artist:
  ///
  /// 	Item artist name
  ///
  /// 	Available if property Type is "audio" or "video"
  ///
  /// :string Album:
  ///
  /// 	Item album name
  ///
  /// 	Available if property Type is "audio" or "video"
  ///
  /// :string Genre:
  ///
  /// 	Item genre name
  ///
  /// 	Available if property Type is "audio" or "video"
  ///
  /// :uint32 NumberOfTracks:
  ///
  /// 	Item album number of tracks in total
  ///
  /// 	Available if property Type is "audio" or "video"
  ///
  /// :uint32 Number:
  ///
  /// 	Item album number
  ///
  /// 	Available if property Type is "audio" or "video"
  ///
  /// :uint32 Duration:
  ///
  /// 	Item duration in milliseconds
  ///
  /// 	Available if property Type is "audio" or "video"
  #[zbus(property)]
  fn metadata(&self)
  -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
}
