//! # D-Bus interface proxy for: `org.bluez.MediaPlayer1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.MediaPlayer1", default_service = "org.bluez")]
pub trait MediaPlayer1 {
  /// Resume playback.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn play(&self) -> zbus::Result<()>;

  /// Pause playback.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn pause(&self) -> zbus::Result<()>;

  /// Stop playback.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn stop(&self) -> zbus::Result<()>;

  /// Next item.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn next(&self) -> zbus::Result<()>;

  /// Previous item.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn previous(&self) -> zbus::Result<()>;

  /// Fast forward playback, this action is only stopped when another method in this
  /// interface is called.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn fast_forward(&self) -> zbus::Result<()>;

  /// Rewind playback, this action is only stopped when another method in this
  /// interface is called.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn rewind(&self) -> zbus::Result<()>;

  /// Press a specific key to send as passthrough command.
  ///
  /// The key will be released automatically. Use Hold() instead if the intention is
  /// to hold down the key.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn press(&self, avc_key: u8) -> zbus::Result<()>;

  /// Press and hold a specific key to send as passthrough command. It is the
  /// responsibility of the caller to make sure that Release() is called after calling
  /// this method.
  ///
  /// The held key will also be released when any other method in this interface is
  /// called.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn hold(&self, avc_key: u8) -> zbus::Result<()>;

  /// Release the previously held key invoked using Hold().
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn release(&self) -> zbus::Result<()>;

  /// Indicates Player Equalizer setting.
  ///
  /// Possible values:
  ///
  /// :"off":
  /// :"on":
  ///
  #[zbus(property)]
  fn equalizer(&self) -> zbus::Result<String>;
  #[zbus(property)]
  fn set_equalizer(&self, value: &str) -> zbus::Result<()>;

  /// Indicates Player Repeat setting.
  ///
  /// Possible values:
  ///
  /// :"off":
  /// :"singletrack":
  /// :"alltracks":
  /// :"group":
  ///
  #[zbus(property)]
  fn repeat(&self) -> zbus::Result<String>;
  #[zbus(property)]
  fn set_repeat(&self, value: &str) -> zbus::Result<()>;

  /// Indicates Player Suffle setting.
  ///
  /// Possible values:
  ///
  /// :"off":
  /// :"alltracks":
  /// :"group":
  ///
  #[zbus(property)]
  fn shuffle(&self) -> zbus::Result<String>;
  #[zbus(property)]
  fn set_shuffle(&self, value: &str) -> zbus::Result<()>;

  /// Indicates Player Scan setting.
  ///
  /// Possible values:
  ///
  /// :"off":
  /// :"alltracks":
  /// :"group":
  ///
  #[zbus(property)]
  fn scan(&self) -> zbus::Result<String>;
  #[zbus(property)]
  fn set_scan(&self, value: &str) -> zbus::Result<()>;

  /// Indicates Player Status setting.
  ///
  /// Possible status:
  ///
  /// :"playing":
  /// :"stopped":
  /// :"paused":
  /// :"forward-seek":
  /// :"reverse-seek":
  /// :"error":
  ///
  #[zbus(property)]
  fn status(&self) -> zbus::Result<String>;

  /// Playback position in milliseconds.
  ///
  /// Changing the position may generate additional events that will be sent to the
  /// remote device. When position is 0 it means the track is starting and when it's
  /// greater than or equal to track's duration the track has ended.
  ///
  /// Note that even if duration is not available in metadata it's possible to signal
  /// its end by setting position to the maximum uint32 value.
  ///
  #[zbus(property)]
  fn position(&self) -> zbus::Result<u32>;

  /// Track metadata.
  ///
  /// Possible values:
  ///
  /// :string Title:
  ///
  /// 	Track title name
  ///
  /// :string Artist:
  ///
  /// 	Track artist name
  ///
  /// :string Album:
  ///
  /// 	Track album name
  ///
  /// :string Genre:
  ///
  /// 	Track genre name
  ///
  /// :uint32 NumberOfTracks:
  ///
  /// 	Number of tracks in total
  ///
  /// :uint32 TrackNumber:
  ///
  /// 	Track number
  ///
  /// :uint32 Duration:
  ///
  /// 	Track duration in milliseconds
  ///
  /// :string ImgHandle: [experimental]
  ///
  /// 	Track image handle, available and valid only during the lifetime of an
  /// 	OBEX BIP connection to the ObexPort.
  ///
  #[zbus(property)]
  fn track(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

  /// Device object path.
  ///
  #[zbus(property)]
  fn device(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Player name.
  ///
  #[zbus(property)]
  fn name(&self) -> zbus::Result<String>;

  /// Player type.
  ///
  /// Possible values:
  ///
  /// :"Audio":
  /// :"Video":
  /// :"Audio Broadcasting":
  /// :"Video Broadcasting":
  ///
  #[zbus(property)]
  fn type_(&self) -> zbus::Result<String>;

  /// Player subtype.
  ///
  /// Possible values:
  ///
  /// :"Audio Book":
  /// :"Podcast":
  ///
  #[zbus(property)]
  fn subtype(&self) -> zbus::Result<String>;

  /// If present indicates the player can be browsed using MediaFolder interface.
  ///
  /// Possible values:
  ///
  /// :True:
  ///
  /// 	Supported and active
  ///
  /// :False:
  ///
  /// 	Supported but inactive
  ///
  /// Note: If supported but inactive clients can enable it by using
  /// **org.bluez.MediaFolder(5)** interface but it might interfere in the playback of
  /// other players.
  ///
  #[zbus(property)]
  fn browsable(&self) -> zbus::Result<bool>;

  /// If present indicates the player can be searched using MediaFolder interface.
  ///
  /// Possible values:
  ///
  /// :True:
  ///
  /// 	Supported and active
  ///
  /// :False:
  ///
  /// 	Supported but inactive
  ///
  /// Note: If supported but inactive clients can enable it by using
  /// **org.bluez.MediaFolder(5)** interface but it might interfere in the playback of
  /// other players.
  ///
  #[zbus(property)]
  fn searchable(&self) -> zbus::Result<bool>;

  /// Playlist object path.
  ///
  #[zbus(property)]
  fn playlist(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// If present indicates the player can get cover art using BIP over OBEX on this
  /// PSM port.
  #[zbus(property)]
  fn obex_port(&self) -> zbus::Result<u16>;
}
