//! # D-Bus interface proxy for: `org.bluez.MediaFolder1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.MediaFolder1", default_service = "org.bluez")]
pub trait MediaFolder1 {
  /// Return a folder object containing the search result.
  ///
  /// To list the items found use the folder object returned and pass to
  /// **ChangeFolder**.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn search(
    &self,
    value: &str,
    filter: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Return a list of items found
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn list_items(
    &self,
    filter: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<
    std::collections::HashMap<
      zbus::zvariant::OwnedObjectPath,
      std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
    >,
  >;

  /// Change current folder.
  ///
  /// Note: By changing folder the items of previous folder might be destroyed and
  /// have to be listed again, the exception is NowPlaying folder which should be
  /// always present while the player is active.
  ///
  /// Possible Errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.Failed:
  ///
  fn change_folder(&self, folder: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

  /// Number of items in the folder
  ///
  #[zbus(property)]
  fn number_of_items(&self) -> zbus::Result<u32>;

  /// Folder name:
  ///
  /// Possible values:
  ///
  /// :"/Filesystem/...":
  ///
  /// 	Filesystem scope
  ///
  /// :"/NowPlaying/...":
  ///
  /// 	NowPlaying scope
  ///
  /// Note: /NowPlaying folder might not be listed if player is stopped, folders
  /// created by Search are virtual so once another Search is perform or the folder is
  /// changed using ChangeFolder it will no longer be listed.
  ///
  #[zbus(property)]
  fn name(&self) -> zbus::Result<String>;
}
