//! # D-Bus interface proxy for: `org.bluez.NetworkServer1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.NetworkServer1", default_service = "org.bluez")]
pub trait NetworkServer1 {
  /// Registers server for the provided UUID.
  ///
  /// Every new connection to this server will be added the bridge interface.
  ///
  /// Possible uuid values:
  ///
  /// :"panu", "00001115-0000-1000-8000-00805f9b34fb":
  ///
  /// 	Personal Network User role.
  ///
  /// :"nap", "00001116-0000-1000-8000-00805f9b34fb":
  ///
  /// 	Network Access Point role.
  ///
  /// :"gn", "00001117-0000-1000-8000-00805f9b34fb":
  ///
  /// 	Group Network role.
  ///
  /// Initially no network server SDP is provided. Only after this method a SDP record
  /// will be available and the BNEP server will be ready for incoming connections.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.AlreadyExists:
  /// :org.bluez.Error.Failed:
  ///
  fn register(&self, uuid: &str, bridge: &str) -> zbus::Result<()>;

  /// Unregisters the server for provided UUID which was previously registered with
  /// **Register()** method.
  ///
  /// All servers will be automatically unregistered when the calling application
  /// terminates.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.Failed:
  fn unregister(&self, uuid: &str) -> zbus::Result<()>;
}
