//! # D-Bus interface proxy for: `org.bluez.Network1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.Network1", default_service = "org.bluez")]
pub trait Network1 {
  /// Connects to the network device and return the network interface name.
  ///
  /// Possible uuid values:
  ///
  /// :"panu", "00001115-0000-1000-8000-00805f9b34fb":
  ///
  /// 	Personal Network User role.
  ///
  /// :"nap", "00001116-0000-1000-8000-00805f9b34fb":
  ///
  /// 	Network Access Point role.
  ///
  /// :"gn", "00001117-0000-1000-8000-00805f9b34fb":
  ///
  /// 	Group Network role.
  ///
  /// The connection will be closed and network device released either upon calling
  /// **Disconnect()** or when the client disappears from the message bus.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.InvalidArguments:
  /// :org.bluez.Error.NotSupported:
  /// :org.bluez.Error.InProgress:
  /// :org.bluez.Error.Failed:
  ///
  fn connect(&self, uuid: &str) -> zbus::Result<String>;

  /// Disconnects from the network device.
  ///
  /// To abort a connection attempt in case of errors or timeouts in the client it is
  /// fine to call this method.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.Failed:
  /// :org.bluez.Error.NotConnected:
  ///
  fn disconnect(&self) -> zbus::Result<()>;

  /// Indicates if the device is connected.
  ///
  #[zbus(property)]
  fn connected(&self) -> zbus::Result<bool>;

  /// Indicates the network interface name when available.
  ///
  #[zbus(property)]
  fn interface(&self) -> zbus::Result<String>;

  /// Indicates the connection role when available.
  #[zbus(property)]
  fn uuid(&self) -> zbus::Result<String>;
}
