//! # D-Bus interface proxy for: `org.bluez.Profile1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.Profile1", default_service = "org.bluez")]
pub trait Profile1 {
  /// This method gets called when **bluetoothd(8)** unregisters the profile.
  ///
  /// A profile can use it to do cleanup tasks. There is no need to unregister the
  /// profile, because when this method gets called it has already been unregistered.
  ///
  fn release(&self) -> zbus::Result<()>;

  /// This method gets called when a new service level connection has been made and
  /// authorized.
  ///
  /// Possible fd_properties values:
  ///
  /// :uint16 Version [optional]:
  ///
  /// 	Profile version.
  ///
  /// :uint16 Features [optional]:
  ///
  /// 	Profile features.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.Error.Rejected:
  /// :org.bluez.Error.Canceled:
  fn new_connection(
    &self,
    device: &zbus::zvariant::ObjectPath<'_>,
    fd: std::os::fd::RawFd,
    fd_properties: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;
}
