//! # D-Bus interface proxy for: `org.bluez.SimAccess1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.SimAccess1", default_service = "org.bluez")]
pub trait SimAccess1 {
  /// Disconnects SAP client from the server.
  ///
  /// Possible errors: org.bluez.Error.Failed
  ///
  fn disconnect(&self) -> zbus::Result<()>;

  /// Indicates if SAP client is connected to the server.
  #[zbus(property)]
  fn connected(&self) -> zbus::Result<bool>;
}
