//! # D-Bus interface proxy for: `org.bluez.ThermometerWatcher1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.ThermometerWatcher1",
  default_service = "org.bluez"
)]
pub trait ThermometerWatcher1 {
  /// This callback gets called when a measurement has been
  /// scanned in the thermometer.
  ///
  /// Measurement:
  ///
  ///     int16 Exponent:
  ///     int32 Mantissa:
  ///
  ///         Exponent and Mantissa values as
  ///         extracted from float value defined by
  ///         IEEE-11073-20601.
  ///
  ///         Measurement value is calculated as
  ///         (Mantissa) * (10^Exponent)
  ///
  ///         For special cases Exponent is
  ///         set to 0 and Mantissa is set to
  ///         one of following values:
  ///
  ///         +(2^23 - 1)    NaN (invalid or
  ///                 missing data)
  ///         -(2^23)        NRes
  ///         +(2^23 - 2)    +Infinity
  ///         -(2^23 - 2)    -Infinity
  ///
  ///     string Unit:
  ///
  ///         Possible values: "celsius" or
  ///                 "fahrenheit"
  ///
  ///     uint64 Time (optional):
  ///
  ///         Time of measurement, if
  ///         supported by device.
  ///         Expressed in seconds since epoch.
  ///
  ///     string Type (optional):
  ///
  ///         Only present if measurement type
  ///         is known.
  ///
  ///         Possible values: "armpit", "body",
  ///             "ear", "finger", "intestines",
  ///             "mouth", "rectum", "toe",
  ///             "tympanum"
  ///
  ///     string Measurement:
  ///
  ///         Possible values: "final" or
  ///                 "intermediate"
  fn measurement_received(
    &self,
    measurement: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
  ) -> zbus::Result<()>;
}
