//! # D-Bus interface proxy for: `org.bluez.ThermometerManager1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(
  interface = "org.bluez.ThermometerManager1",
  default_service = "org.bluez"
)]
pub trait ThermometerManager1 {
  /// Registers a watcher to monitor scanned measurements.
  /// This agent will be notified about final temperature
  /// measurements.
  ///
  /// Possible Errors: org.bluez.Error.InvalidArguments
  ///
  /// UnregisterWatcher(object agent)
  ///
  /// Unregisters a watcher.
  ///
  /// EnableIntermediateMeasurement(object agent)
  ///
  /// Enables intermediate measurement notifications
  /// for this agent. Intermediate measurements will
  /// be enabled only for thermometers which support it.
  ///
  /// Possible Errors: org.bluez.Error.InvalidArguments
  ///
  /// DisableIntermediateMeasurement(object agent)
  ///
  /// Disables intermediate measurement notifications
  /// for this agent. It will disable notifications in
  /// thermometers when the last agent removes the
  /// watcher for intermediate measurements.
  ///
  /// Possible Errors: org.bluez.Error.InvalidArguments
  ///         org.bluez.Error.NotFound
  ///
  fn register_watcher(&self, agent: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;
}
