//! # D-Bus interface proxy for: `org.bluez.Thermometer1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.Thermometer1", default_service = "org.bluez")]
pub trait Thermometer1 {
  /// True if the thermometer supports intermediate
  /// measurement notifications.
  ///
  #[zbus(property)]
  fn intermediate(&self) -> zbus::Result<bool>;

  /// The Measurement Interval defines the time (in
  /// seconds) between measurements. This interval is
  /// not related to the intermediate measurements and
  /// must be defined into a valid range. Setting it
  /// to zero means that no periodic measurements will
  /// be taken.
  ///
  #[zbus(property)]
  fn interval(&self) -> zbus::Result<u16>;
  #[zbus(property)]
  fn set_interval(&self, value: u16) -> zbus::Result<()>;

  /// Defines the maximum value allowed for the interval
  /// between periodic measurements.
  ///
  #[zbus(property)]
  fn maximum(&self) -> zbus::Result<u16>;

  /// Defines the minimum value allowed for the interval
  /// between periodic measurements.
  ///
  #[zbus(property)]
  fn minimum(&self) -> zbus::Result<u16>;
}
