//! # D-Bus interface proxy for: `org.bluez.obex.Agent1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.Agent1", default_service = "org.bluez")]
pub trait Agent1 {

  /// This method gets called when **obexd(8)** daemon unregisters the agent.
  ///
  /// An agent can use it to do cleanup tasks. There is no need to unregister the
  /// agent, because when this method gets called it has already been unregistered.
  ///
  fn release(&self) -> zbus::Result<()>;

  /// This method gets called when the **obexd(8)** needs to accept/reject a Bluetooth
  /// object push request.
  ///
  /// Returns the full path (including the filename) or the folder name suffixed with
  /// '/' where the object shall be stored.
  ///
  /// The transfer object, see **org.bluez.obex.Transfer(5)** will contain a Filename
  /// property that contains the default location and name that can be returned.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.Rejected:
  /// :org.bluez.obex.Error.Canceled:
  ///
  fn authorize_push(&self, transfer: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<String>;

  /// This method gets called to indicate that the agent request failed before a reply
  /// was returned. It cancels the previous request.
  fn cancel(&self) -> zbus::Result<()>;
}
