//! # D-Bus interface proxy for: `org.bluez.obex.AgentManager1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.AgentManager1", default_service = "org.bluez")]
pub trait AgentManager1 {

  /// Registers an agent, which must implement **org.bluez.obex.Agent(5)**, to request
  /// authorization of the user to accept/reject objects.
  ///
  /// Object push service needs to authorize each received object.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.AlreadyExists:
  ///
  fn register_agent(&self, agent: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

  /// Unregisters the agent that has been previously registered using
  /// **RegisterAgent()**.
  ///
  /// The object path parameter must match the same value that has been used on
  /// registration.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.DoesNotExist:
  fn unregister_agent(&self, agent: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;
}
