//! # D-Bus interface proxy for: `org.bluez.obex.Client1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.Client1", default_service = "org.bluez")]
pub trait Client1 {

  /// Connects to the destination address and then proceed to create an OBEX session
  /// object which implements **org.bluez.obex.Session(5)** interface.
  ///
  /// The last parameter is a dictionary to hold optional or type-specific parameters.
  ///
  /// Possible args values:
  ///
  /// :string Target:
  ///
  /// 	Type of session to be created.
  ///
  /// 	Possible values:
  ///
  /// 	:"ftp":
  /// 	:"map":
  /// 	:"opp":
  /// 	:"pbap":
  /// 	:"sync":
  /// 	:"bip-avrcp":
  ///
  /// :string Source:
  ///
  /// 	Local address to be used.
  ///
  /// :byte Channel:
  ///
  /// 	Channel to be used.
  ///
  /// :uint16 PSM:
  ///
  /// 	L2CAP PSM to be used.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn create_session(&self, destination: &str, args: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Disconnects and removes session previously created by **CreateSession()**
  /// aborting any pending transfers.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.NotAuthorized:
  fn remove_session(&self, session: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;
}
