//! # D-Bus interface proxy for: `org.bluez.obex.FileTransfer1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.FileTransfer1", default_service = "org.bluez")]
pub trait FileTransfer1 {

  /// Changes the current folder of the remote device.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn change_folder(&self, folder: &str) -> zbus::Result<()>;

  /// Creates a new folder in the remote device.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn create_folder(&self, folder: &str) -> zbus::Result<()>;

  /// Returns a dictionary containing information about the current folder content.
  ///
  /// Possible return values:
  ///
  /// :string Name:
  ///
  /// 	Object name in UTF-8 format.
  ///
  /// :string Type:
  ///
  /// 	Either "folder" or "file".
  ///
  /// :uint64 Size:
  ///
  /// 	Object size or number of items in folder.
  ///
  /// :string Permission:
  ///
  /// 	Group, owner and other permission.
  ///
  /// :uint64 Modified:
  ///
  /// 	Last change.
  ///
  /// :uint64 Accessed:
  ///
  /// 	Last access.
  ///
  /// :uint64 Created:
  ///
  /// 	Creation date.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.Failed:
  ///
  fn list_folder(&self) -> zbus::Result<Vec<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>>;

  /// Copies the contents of the source file (from remote device) to the target file
  /// (on local filesystem).
  ///
  /// If an empty target file is given, a name will be automatically generated for the
  /// temporary file.
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn get_file(&self, targetfile: &str, sourcefile: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;

  /// Copies the contents of the source file (from local filesystem) to the target
  /// file (on remote device).
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn put_file(&self, sourcefile: &str, targetfile: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;

  /// Copies the contents from source file to target file on the remote device.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn copy_file(&self, sourcefile: &str, targetfile: &str) -> zbus::Result<()>;

  /// Moves a file within the remote device from source file to the target file.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn move_file(&self, sourcefile: &str, targetfile: &str) -> zbus::Result<()>;

  /// Deletes the specified file/folder.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  fn delete(&self, file: &str) -> zbus::Result<()>;
}
