//! # D-Bus interface proxy for: `org.bluez.obex.Image1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.Image1", default_service = "org.bluez")]
pub trait Image1 {

  /// Retrieves the image corresponding to the handle and the description, as one of
  /// the descriptions retrieved by GetImageProperties, and store it in a local file.
  ///
  /// If the "transform" property description exists it should be set to one of the
  /// value listed by GetImageProperties for this description.
  ///
  /// If description is an empty dict, the native image will be retrieved.
  ///
  /// 	Possible errors:
  ///
  /// 	:org.bluez.obex.Error.InvalidArguments:
  /// 	:org.bluez.obex.Error.Failed:
  ///
  fn get(&self, targetfile: &str, handle: &str, description: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;

  /// Retrieves the image properties corresponding to the handle.
  ///
  /// The first dict entry is mandatory and correspond to 'handle' and 'name' of the
  /// image.
  ///
  /// The second dict entry is mandatory and correspond to the native description
  /// ('type':'native') of the image.
  ///
  /// The following dict entries are optional and correspond to variant descriptions
  /// of the image. If the 'transform' entry exists in the description, it lists the
  /// available possible image transformations and should be set to one of them before
  /// using the description as parameter to **GetImage**.
  ///
  /// Possible property values:
  ///
  /// :string type:
  ///
  /// 	Type of dict properties. Mandatory for each dict.
  ///
  /// 	Possible values:
  ///
  /// 	:"native":
  /// 	:"variant":
  ///
  /// :string encoding:
  ///
  /// 	File encoding format.
  ///
  /// 	Possible values:
  ///
  /// 	:"BMP":
  /// 	:"GIF":
  /// 	:"JPEG":
  /// 	:"JPEG2000":
  /// 	:"PNG":
  /// 	:"WBMP":
  ///
  /// :string pixel:
  ///
  /// 	File encoding format size of form "<width>*<height>".
  ///
  /// :uint64 size:
  ///
  /// 	File size.
  ///
  /// :uint64 maxsize:
  ///
  /// 	File maximum size.
  ///
  /// :string transformation:
  ///
  /// 	List of available transformations separated by space.
  ///
  /// 	Possible values:
  ///
  /// 	:"crop":
  /// 	:"fill":
  /// 	:"stretch":
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn properties(&self, handle: &str) -> zbus::Result<Vec<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>>;

  /// Retrieves the image thumbnail corresponding to the handle and store it in a
  /// local file.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  fn get_thumbnail(&self, targetfile: &str, handle: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;
}
