//! # D-Bus interface proxy for: `org.bluez.obex.Message1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.Message1", default_service = "org.bluez")]
pub trait Message1 {

  /// Download message and store it in the target file.
  ///
  /// If an empty target file is given, a temporary file will be automatically
  /// generated.
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn get(&self, targetfile: &str, attachment: bool) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;

  /// Folder which the message belongs to
  ///
  #[zbus(property)]
  fn folder(&self) -> zbus::Result<String>;

  /// Message subject
  ///
  #[zbus(property)]
  fn subject(&self) -> zbus::Result<String>;

  /// Message timestamp
  ///
  #[zbus(property)]
  fn timestamp(&self) -> zbus::Result<String>;

  /// Message sender name
  ///
  #[zbus(property)]
  fn sender(&self) -> zbus::Result<String>;

  /// Message sender address
  ///
  #[zbus(property)]
  fn sender_address(&self) -> zbus::Result<String>;

  /// Message Reply-To address
  ///
  #[zbus(property)]
  fn reply_to(&self) -> zbus::Result<String>;

  /// Message recipient name
  ///
  #[zbus(property)]
  fn recipient(&self) -> zbus::Result<String>;

  /// Message recipient address
  ///
  #[zbus(property)]
  fn recipient_address(&self) -> zbus::Result<String>;

  /// Message type
  ///
  /// Possible values:
  ///
  /// :"email":
  /// :"sms-gsm":
  /// :"sms-cdma":
  /// :"mms":
  ///
  #[zbus(property)]
  fn type_(&self) -> zbus::Result<String>;

  /// Message size in bytes
  ///
  #[zbus(property)]
  fn size(&self) -> zbus::Result<u64>;

  /// Message reception status
  ///
  /// Possible values:
  ///
  /// :"complete":
  /// :"fractioned":
  /// :"notification":
  ///
  #[zbus(property)]
  fn status(&self) -> zbus::Result<String>;

  /// Message priority flag
  ///
  #[zbus(property)]
  fn priority(&self) -> zbus::Result<bool>;

  /// Message read flag
  ///
  #[zbus(property)]
  fn read(&self) -> zbus::Result<bool>;
  #[zbus(property)]
  fn set_read(&self, value: bool) -> zbus::Result<()>;

  /// Message deleted flag
  ///
  #[zbus(property)]
  fn deleted(&self) -> zbus::Result<bool>;
  #[zbus(property)]
  fn set_deleted(&self, value: bool) -> zbus::Result<()>;

  /// Message sent flag
  ///
  #[zbus(property)]
  fn sent(&self) -> zbus::Result<bool>;

  /// Message protected flag
  ///
  #[zbus(property)]
  fn protected(&self) -> zbus::Result<bool>;

  /// Message delivery status
  ///
  /// Possible values:
  ///
  /// :"delivered":
  /// :"sent":
  /// :"unknown":
  ///
  #[zbus(property)]
  fn delivery_status(&self) -> zbus::Result<String>;

  /// Message conversation id sent by Server which servers as Unique identification of
  /// the conversation.
  ///
  #[zbus(property)]
  fn conversation_id(&self) -> zbus::Result<u64>;

  /// Human readable name of the conversation
  ///
  #[zbus(property)]
  fn conversation_name(&self) -> zbus::Result<String>;

  /// Indicate the direction of the message
  ///
  /// Possible values:
  ///
  /// :"incoming":
  /// :"outgoing":
  /// :"outgoingdraft":
  /// :"outgoingpending":
  ///
  #[zbus(property)]
  fn direction(&self) -> zbus::Result<String>;

  /// MIME type of the attachment
  #[zbus(property)]
  fn attachment_mime_types(&self) -> zbus::Result<String>;
}
