//! # D-Bus interface proxy for: `org.bluez.obex.ObjectPush1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.ObjectPush1", default_service = "org.bluez")]
pub trait ObjectPush1 {

  /// Sends local file to the remote device.
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn send_file(&self, sourcefile: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;

  /// Request the business card from a remote device and store it in the local file.
  ///
  /// If an empty target file is given, a name will be automatically generated for the
  /// temporary file.
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn pull_business_card(&self, targetfile: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;

  /// Push the client's business card to the remote device and then retrieve the
  /// remote business card and store it in a local file.
  ///
  /// If an empty target file is given, a name will be automatically generated for the
  /// temporary file.
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  fn exchange_business_cards(&self, clientfile: &str, targetfile: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;
}
