//! # D-Bus interface proxy for: `org.bluez.obex.Session1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.Session1", default_service = "org.bluez")]
pub trait Session1 {

  /// Get remote device capabilities.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.NotSupported:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn get_capabilities(&self) -> zbus::Result<String>;

  /// Bluetooth adapter address
  ///
  #[zbus(property)]
  fn source(&self) -> zbus::Result<String>;

  /// Bluetooth device address
  ///
  #[zbus(property)]
  fn destination(&self) -> zbus::Result<String>;

  /// Bluetooth channel
  ///
  #[zbus(property)]
  fn channel(&self) -> zbus::Result<u8>;

  /// Bluetooth L2CAP PSM
  ///
  #[zbus(property)]
  fn psm(&self) -> zbus::Result<u16>;

  /// Target UUID
  ///
  #[zbus(property)]
  fn target(&self) -> zbus::Result<String>;

  /// Root path
  #[zbus(property)]
  fn root(&self) -> zbus::Result<String>;
}
