//! # D-Bus interface proxy for: `org.bluez.obex.Synchronization1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.Synchronization1", default_service = "org.bluez")]
pub trait Synchronization1 {

  /// Sets the phonebook object store location for other operations. Should be called
  /// before all the other operations.
  ///
  /// Possible location:
  ///
  /// :"int" ( "internal" which is default ):
  ///
  /// 	Store in the interval memory.
  ///
  /// :"sim{#}":
  ///
  /// 	Store in sim card number #.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  ///
  fn set_location(&self, location: &str) -> zbus::Result<()>;

  /// Retrieves an entire Phonebook Object store from remote device, and stores it in
  /// a local file.
  ///
  /// If an empty target file is given, a name will be automatically calculated for
  /// the temporary file.
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn get_phonebook(&self, targetfile: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;

  /// Sends an entire Phonebook Object store to remote device.
  ///
  /// The returned path represents the newly created transfer, which should be used to
  /// find out if the content has been successfully transferred or if the operation
  /// fails.
  ///
  /// The properties of this transfer are also returned along with the object path, to
  /// avoid a call to GetProperties, see **org.bluez.obex.Transfer(5)** for the
  /// possible list of properties.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.InvalidArguments:
  /// :org.bluez.obex.Error.Failed:
  fn put_phonebook(&self, sourcefile: &str) -> zbus::Result<(zbus::zvariant::OwnedObjectPath, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>;
}
