//! # D-Bus interface proxy for: `org.bluez.obex.Transfer1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.obex.Transfer1", default_service = "org.bluez")]
pub trait Transfer1 {

  /// Cancels the current transference.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.NotAuthorized:
  /// :org.bluez.obex.Error.InProgress:
  /// :org.bluez.obex.Error.Failed:
  ///
  fn cancel(&self) -> zbus::Result<()>;

  /// Suspends transference.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.NotAuthorized:
  /// :org.bluez.obex.Error.NotInProgress:
  ///
  /// 	If transfer is still in with **Status** **"queued"**.
  ///
  fn suspend(&self) -> zbus::Result<()>;

  /// Resumes transference previously suspended with use of **Suspend()** method.
  ///
  /// Possible errors:
  ///
  /// :org.bluez.obex.Error.NotAuthorized:
  /// :org.bluez.obex.Error.NotInProgress:
  ///
  /// 	If transfer is still in with **Status** **"queued"**.
  ///
  fn resume(&self) -> zbus::Result<()>;

  /// Indicates the current status of the transfer.
  ///
  /// Possible values:
  ///
  /// 	:"queued":
  /// 	:"active":
  /// 	:"suspended":
  /// 	:"complete":
  /// 	:"error":
  ///
  #[zbus(property)]
  fn status(&self) -> zbus::Result<String>;

  /// The object path of the session the transfer belongs to.
  ///
  #[zbus(property)]
  fn session(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

  /// Name of the object being transferred.
  ///
  /// Either Name or Type or both will be present.
  ///
  #[zbus(property)]
  fn name(&self) -> zbus::Result<String>;

  /// Type of the object transferred being transferred.
  ///
  /// Either Name or Type or both will be present.
  ///
  #[zbus(property)]
  fn type_(&self) -> zbus::Result<String>;

  /// Time of the object being transferred if this is provided by the remote party.
  ///
  #[zbus(property)]
  fn time(&self) -> zbus::Result<u64>;

  /// Size of the object being transferred.
  ///
  /// If the size is unknown, then this property will not be present.
  ///
  #[zbus(property)]
  fn size(&self) -> zbus::Result<u64>;

  /// Number of bytes transferred.
  ///
  /// For transfers with **Status** set to **"queued"**, this value will not be
  /// present.
  ///
  #[zbus(property)]
  fn transferred(&self) -> zbus::Result<u64>;

  /// Complete name of the file being received or sent.
  ///
  /// For incoming object push transaction, this will be the proposed default location
  /// and name. It can be overwritten by the **AuthorizePush()** in
  /// **org.bluez.obex.Agent(5)** and will be then updated accordingly.
  #[zbus(property)]
  fn filename(&self) -> zbus::Result<String>;
}
