//! # D-Bus interface proxy for: `org.bluez.mesh.Application1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.mesh.Application1", default_service = "org.bluez")]
pub trait Application1 {

  /// This method is called when the node provisioning initiated
  /// by a Join() method call successfully completed.
  ///
  /// The token parameter serves as a unique identifier of the
  /// particular node. The token must be preserved by the application
  /// in order to authenticate itself to the mesh daemon and attach to
  /// the network as a mesh node by calling Attach() method or
  /// permanently remove the identity of the mesh node by calling
  /// Leave() method.
  ///
  /// If this method returns an error, the daemon will assume that the
  /// application failed to preserve the token, and will remove the
  /// freshly created node.
  ///
  fn join_complete(&self, token: u64) -> zbus::Result<()>;

  /// This method is called when the node provisioning initiated by
  /// Join() has failed.
  ///
  /// The reason parameter identifies the reason for provisioning
  /// failure. The defined values are: "timeout", "bad-pdu",
  /// "confirmation-failed", "out-of-resources", "decryption-error",
  /// "unexpected-error", "cannot-assign-addresses".
  ///
  fn join_failed(&self, reason: &str) -> zbus::Result<()>;

  /// A 16-bit Bluetooth-assigned Company Identifier of the vendor as
  /// defined by Bluetooth SIG
  ///
  #[zbus(property)]
  fn company_id(&self) -> zbus::Result<u16>;

  /// A 16-bit vendor-assigned product identifier
  ///
  #[zbus(property)]
  fn product_id(&self) -> zbus::Result<u16>;

  /// A 16-bit vendor-assigned product version identifier
  ///
  #[zbus(property)]
  fn version_id(&self) -> zbus::Result<u16>;

  /// A 16-bit minimum number of replay protection list entries
  ///
  #[zbus(property)]
  fn crpl(&self) -> zbus::Result<u16>;
}
