//! # D-Bus interface proxy for: `org.bluez.mesh.Attention1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.mesh.Attention1", default_service = "org.bluez")]
pub trait Attention1 {

  /// The element_index parameter is the element's index within the
  /// node where the health server model is hosted.
  ///
  /// The time parameter indicates how many seconds the attention
  /// state shall be on.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.NotSupported
  ///
  fn set_timer(&self, element_index: u8, time: u16) -> zbus::Result<()>;

  /// The element parameter is the unicast address within the node
  /// where the health server model is hosted.
  ///
  /// Returns the number of seconds for how long the attention action
  /// remains staying on.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.NotSupported
  ///
  fn get_timer(&self, element: u16) -> zbus::Result<u16>;
}
