//! # D-Bus interface proxy for: `org.bluez.mesh.Element1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.mesh.Element1", default_service = "org.bluez")]
pub trait Element1 {

  /// This method is called by bluetooth-meshd daemon when a message
  /// arrives addressed to the application.
  ///
  /// The source parameter is unicast address of the remote
  /// node-element that sent the message.
  ///
  /// The key_index parameter indicates which application key has been
  /// used to decode the incoming message. The same key_index should
  /// be used by the application when sending a response to this
  /// message (in case a response is expected).
  ///
  /// The destination parameter contains the destination address of
  /// received message. Underlying variant types are:
  ///
  /// uint16
  ///
  ///     Destination is an unicast address, or a well known
  ///     group address
  ///
  /// array{byte}
  ///
  ///     Destination is a virtual address label
  ///
  /// The data parameter is the incoming message.
  ///
  fn message_received(&self, source: u16, key_index: u16, destination: &zbus::zvariant::Value<'_>, data: &[u8]) -> zbus::Result<()>;

  /// This method is called by meshd daemon when a message arrives
  /// addressed to the application, which was sent with the remote
  /// node's device key.
  ///
  /// The source parameter is unicast address of the remote
  /// node-element that sent the message.
  ///
  /// The remote parameter if true indicates that the device key
  /// used to decrypt the message was from the sender. False
  /// indicates that the local nodes device key was used, and the
  /// message has permissions to modify local states.
  ///
  /// The net_index parameter indicates what subnet the message was
  /// received on, and if a response is required, the same subnet
  /// must be used to send the response.
  ///
  /// The data parameter is the incoming message.
  ///
  fn dev_key_message_received(&self, source: u16, remote: bool, net_index: u16, data: &[u8]) -> zbus::Result<()>;

  /// This method is called by bluetooth-meshd daemon when a model's
  /// configuration is updated.
  ///
  /// The model_id parameter contains BT SIG Model Identifier or, if
  /// Vendor key is present in config dictionary, a 16-bit
  /// vendor-assigned Model Identifier.
  ///
  /// The config parameter is a dictionary with the following keys
  /// defined:
  ///
  /// array{uint16} Bindings
  ///
  ///     Indices of application keys bound to the model
  ///
  /// uint32 PublicationPeriod
  ///
  ///     Model publication period in milliseconds
  ///
  /// uint16 Vendor
  ///
  ///     A 16-bit Bluetooth-assigned Company Identifier of the
  ///     vendor as defined by Bluetooth SIG
  ///
  /// array{variant} Subscriptions
  ///
  ///     Addresses the model is subscribed to.
  ///
  ///     Each address is provided either as uint16 for group
  ///     addresses, or as array{byte} for virtual labels.
  ///
  fn update_model_configuration(&self, model_id: u16, config: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>) -> zbus::Result<()>;

  /// Element index. It is required that the application follows
  /// sequential numbering scheme for the elements, starting with 0.
  ///
  #[zbus(property)]
  fn index(&self) -> zbus::Result<u8>;

  /// An array of SIG Models:
  ///
  ///     id - SIG Model Identifier
  ///
  ///     options - a dictionary that may contain additional model
  ///     info. The following keys are defined:
  ///
  ///         boolean Publish - indicates whether the model
  ///             supports publication mechanism. If not
  ///             present, publication is enabled.
  ///
  ///         boolean Subscribe - indicates whether the model
  ///             supports subscription mechanism. If not
  ///             present, subscriptons are enabled.
  ///
  /// The array may be empty.
  ///
  #[zbus(property)]
  fn models(&self) -> zbus::Result<Vec<(u16, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>>;

  /// An array of Vendor Models:
  ///
  ///     vendor - a 16-bit Bluetooth-assigned Company ID as
  ///     defined by Bluetooth SIG.
  ///
  ///     id - a 16-bit vendor-assigned Model Identifier
  ///
  ///     options - a dictionary that may contain additional model
  ///     info. The following keys are defined:
  ///
  ///         boolean Publish - indicates whether the model
  ///             supports publication mechanism
  ///
  ///         boolean Subscribe - indicates whether the model
  ///             supports subscription mechanism
  ///
  /// The array may be empty.
  ///
  #[zbus(property)]
  fn vendor_models(&self) -> zbus::Result<Vec<(u16, u16, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>>;

  /// Location descriptor as defined in the GATT Bluetooth Namespace
  /// Descriptors section of the Bluetooth SIG Assigned Numbers
  ///
  #[zbus(property)]
  fn location(&self) -> zbus::Result<u16>;
}
