//! # D-Bus interface proxy for: `org.bluez.mesh.Management1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.mesh.Management1", default_service = "org.bluez")]
pub trait Management1 {

  /// This method is used by the application that supports
  /// org.bluez.mesh.Provisioner1 interface to start listening
  /// (scanning) for unprovisioned devices in the area.
  ///
  /// The options parameter is a dictionary with the following keys
  /// defined:
  ///
  /// uint16 Seconds
  ///     Specifies number of seconds for scanning to be active.
  ///     If set to 0 or if this key is not present, then the
  ///     scanning will continue until UnprovisionedScanCancel()
  ///     or AddNode() methods are called. If not present, and a
  ///     remote server is specified, the default timeout will be
  ///     60 seconds.
  ///
  /// uint16 Server
  ///     Specifies a remote server on which to perform scanning.
  ///     If not present, scanning will be local. If present,
  ///     the timeout must be between 1 and 60 seconds.
  ///
  /// uint16 Subnet
  ///     Specifies a subnet for the remote server. If not
  ///     present, primary subnet will be used. If Server not
  ///     present, the Subnet will be ignored.
  ///
  /// array{byte}[16] Filter
  ///     Specifies a specific UUID to search for. If not
  ///     present, all found UUIDs will be returned.
  ///
  /// uint8 array Extended
  ///     Specifies variable number of Bluetooth AD types to
  ///     return with scan result. Only valid if a Filter has been
  ///     specified.
  ///
  /// Each time a unique unprovisioned beacon is heard, the
  /// ScanResult() method on the app will be called with the result.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotAuthorized
  ///     org.bluez.mesh.Error.Busy
  ///
  fn unprovisioned_scan(&self, options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>) -> zbus::Result<()>;

  /// This method is used by the application that supports
  /// org.bluez.mesh.Provisioner1 interface to stop listening
  /// (scanning) for unprovisioned devices in the area.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotAuthorized
  ///
  fn unprovisioned_scan_cancel(&self) -> zbus::Result<()>;

  /// This method is used by the application that supports
  /// org.bluez.mesh.Provisioner1 interface to add the
  /// unprovisioned device specified by uuid, to the Network.
  ///
  /// The uuid parameter is a 16-byte array that contains Device UUID
  /// of the unprovisioned device to be added to the network.
  ///
  /// The options parameter is a dictionary that may contain
  /// additional optional configuration info:
  ///
  /// uint16 Server
  ///     Specifies a remote server to perform provisioning on. If
  ///     not present, provisioning will be done locally.
  ///
  /// uint16 Subnet
  ///     Specifies a subnet for the remote server. If not
  ///     present, primary subnet will be used. If Server not
  ///     present Subnet will be ignored.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotAuthorized
  ///
  fn add_node(&self, uuid: &[u8], options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>) -> zbus::Result<()>;

  /// This method is used by the application that supports
  /// org.bluez.mesh.Provisioner1 interface to perform one of the
  /// Node Provisioning Protocol Interface procedures with a remote
  /// node to refresh its device key, unicast address, and
  /// composition. Remote node being reprovisioned must have the
  /// Remote Provisioning Server model.
  ///
  /// The unicast parameter is the 16-bit primary node address of
  /// the remote node being reprovisioned.
  ///
  /// The options parameter is a dictionary that may contain
  /// additional optional configuration info:
  ///
  /// uint8 NPPI
  ///     Specifies the Node Provisioning Protocol Interface
  ///     procedure, as defined in the Mesh Profile Specification:
  ///         0 - Device Key Refresh Only
  ///         1 - Node Address Refresh
  ///         2 - Node Composition Refresh
  ///
  ///     If not present, procedure 0 will be used.
  ///
  /// uint16 Subnet
  ///     Specifies the subnet remote node is on. If not
  ///     present, primary subnet will be tried.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotAuthorized
  ///
  fn reprovision(&self, unicast: u16, options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>) -> zbus::Result<()>;

  /// This method is used by the application to generate and add a new
  /// network subnet key.
  ///
  /// The net_index parameter is a 12-bit value (0x001-0xFFF)
  /// specifying which net key to add.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.AlreadyExists
  ///
  fn create_subnet(&self, net_index: u16) -> zbus::Result<()>;

  /// This method is used by the application to add a network subnet
  /// key, that was originally generated by a remote Config Client.
  ///
  /// The net_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which net key to add.
  ///
  /// The net_key parameter is the 16-byte value of the net key being
  /// imported.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.AlreadyExists
  ///
  fn import_subnet(&self, net_index: u16, net_key: &[u8]) -> zbus::Result<()>;

  /// This method is used by the application to generate a new network
  /// subnet key, and set it's key refresh state to Phase 1.
  ///
  /// The net_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which net key to update. Note that the subnet must
  /// exist prior to updating.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.DoesNotExist
  ///     org.bluez.mesh.Error.Busy
  ///
  fn update_subnet(&self, net_index: u16) -> zbus::Result<()>;

  /// This method is used by the application that to delete a subnet.
  ///
  /// The net_index parameter is a 12-bit value (0x001-0xFFF)
  /// specifying which net key to delete. The primary net key (0x000)
  /// may not be deleted.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///
  fn delete_subnet(&self, net_index: u16) -> zbus::Result<()>;

  /// to CompleteAppKeyUpdate() on all app keys that have been
  /// updated during the procedure prior to setting phase 3.
  ///
  /// The net_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which subnet phase to set.
  ///
  /// The phase parameter is used to cycle the local key database
  /// through the phases as defined by the Mesh Profile Specification.
  /// Allowed values:
  ///     0 - Cancel Key Refresh (May only be called from Phase 1,
  ///         and should never be called once the new key has
  ///         started propagating)
  ///     1 - Invalid Argument (see NetKeyUpdate method)
  ///     2 - Go to Phase 2 (May only be called from Phase 1)
  ///     3 - Complete Key Refresh procedure (May only be called
  ///         from Phase 2)
  ///
  /// This call affects the local bluetooth-meshd key database only.
  /// It is the responsibility of the application to maintain the key
  /// refresh phases per the Mesh Profile Specification.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.DoesNotExist
  ///
  fn set_key_phase(&self, net_index: u16, phase: u8) -> zbus::Result<()>;

  /// This method is used by the application to generate and add a new
  /// application key.
  ///
  /// The net_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which net key to bind the application key to.
  ///
  /// The app_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which app key to add.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.AlreadyExists
  ///     org.bluez.mesh.Error.DoesNotExist
  ///
  fn create_app_key(&self, net_index: u16, app_index: u16) -> zbus::Result<()>;

  /// This method is used by the application to add an application
  /// key, that was originally generated by a remote Config Client.
  ///
  /// The net_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which net key to bind the application key to.
  ///
  /// The app_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which app key to import.
  ///
  /// The app_key parameter is the 16-byte value of the key being
  /// imported.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.AlreadyExists
  ///     org.bluez.mesh.Error.DoesNotExist
  ///
  fn import_app_key(&self, net_index: u16, app_index: u16, app_key: &[u8]) -> zbus::Result<()>;

  /// This method is used by the application to generate a new
  /// application key.
  ///
  /// The app_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which app key to update. Note that the subnet that
  /// the key is bound to must exist and be in Phase 1.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.DoesNotExist
  ///     org.bluez.mesh.Error.InProgress
  ///
  fn update_app_key(&self, app_index: u16) -> zbus::Result<()>;

  /// This method is used by the application to delete an application
  /// key.
  ///
  /// The app_index parameter is a 12-bit value (0x000-0xFFF)
  /// specifying which app key to delete.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///
  fn delete_app_key(&self, app_index: u16) -> zbus::Result<()>;

  /// This method is used by the application to import a remote node
  /// that has been provisioned by an external process.
  ///
  /// The primary parameter specifies the unicast address of the
  /// the node being imported.
  ///
  /// The count parameter specifies the number of elements that are
  /// assigned to this remote node.
  ///
  /// The device_key parameter is the access layer key that will be
  /// used to decrypt privileged messages from this remote node.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// It is an error to call this with address range overlapping
  /// with local element addresses.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.Failed
  ///     org.bluez.mesh.Error.InvalidArguments
  ///
  fn import_remote_node(&self, primary: u16, count: u8, device_key: &[u8]) -> zbus::Result<()>;

  /// This method is used by the application to delete a remote node
  /// from the local device key database.
  ///
  /// The primary parameter specifies the unicast address of the
  /// the node being deleted.
  ///
  /// The count parameter specifies the number of elements that were
  /// assigned to the remote node.
  ///
  /// This call affects the local bluetooth-meshd key database only.
  ///
  /// It is an error to call this with address range overlapping
  /// with local element addresses.
  ///
  /// PossibleErrors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///
  fn delete_remote_node(&self, primary: u16, count: u8) -> zbus::Result<()>;

  /// This method is used by the application to export information
  /// about network keys, application keys and device keys present
  /// in the local key database.
  ///
  /// dict
  ///     A dictionary that contains information for the keys
  ///     stored in the keyring with the following keys defined:
  ///
  ///     NetKeys:
  ///         array{struct} net_keys:
  ///
  ///         uint16 index
  ///             Subnet index
  ///
  ///         array{byte}[16] key
  ///
  ///         dict:
  ///             A dictionary that contains optional
  ///             key info with the following keys
  ///             defined:
  ///
  ///             uint8 Phase
  ///                 Key Refresh phase of the subnet
  ///
  ///             array{byte}[16] OldKey
  ///
  ///             array{struct} AppKeys:
  ///
  ///                 uint16 index
  ///
  ///                     Application key index
  ///
  ///                 array{byte}[16] key
  ///
  ///                 dict:
  ///                     A dictionary of optional
  ///                     key info with the
  ///                     following keys defined:
  ///
  ///                     array{byte}[16] OldKey
  ///
  ///     DevKeys:
  ///         array{struct} dev_keys:
  ///
  ///         Device Key information for known remote
  ///         nodes in the configured Mesh network
  ///
  ///         uint16 unicast
  ///
  ///             Unicast address of the node's primary
  ///             element
  ///
  ///         array{byte}[16] key
  ///
  fn export_keys(&self) -> zbus::Result<(Vec<(u16, Vec<u8>, std::collections::HashMap<String, zbus::zvariant::OwnedValue>)>, Vec<(u16, Vec<u8>)>)>;
}
