//! # D-Bus interface proxy for: `org.bluez.mesh.Node1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.mesh.Node1", default_service = "org.bluez")]
pub trait Node1 {

  /// This method is used to send a message originated by a local
  /// model.
  ///
  /// The element_path parameter is the object path of an element from
  /// a collection of the application elements (see Mesh Application
  /// Hierarchy section).
  ///
  /// The destination parameter contains the destination address. This
  /// destination must be a uint16 to a unicast address, or a well
  /// known group address.
  ///
  /// The key_index parameter determines which application key to use
  /// for encrypting the message. The key_index must be valid for that
  /// element, i.e., the application key must be bound to a model on
  /// this element. Otherwise, org.bluez.mesh.Error.NotAuthorized will
  /// be returned.
  ///
  /// The options parameter is a dictionary with the following keys
  /// defined:
  ///
  ///     bool ForceSegmented
  ///         Specifies whether to force sending of a short
  ///         message as one-segment payload. If not present,
  ///         the default setting is "false".
  ///
  /// The data parameter is an outgoing message to be encrypted by the
  /// bluetooth-meshd daemon and sent on.
  ///
  /// Possible errors:
  ///     org.bluez.mesh.Error.NotAuthorized
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotFound
  ///
  fn send(&self, element_path: &zbus::zvariant::ObjectPath<'_>, destination: u16, key_index: u16, options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>, data: &[u8]) -> zbus::Result<()>;

  /// This method is used to send a message originated by a local
  /// model encoded with the device key of the remote node.
  ///
  /// The element_path parameter is the object path of an element from
  /// a collection of the application elements (see Mesh Application
  /// Hierarchy section).
  ///
  /// The destination parameter contains the destination address. This
  /// destination must be a uint16 to a unicast address, or a well
  /// known group address.
  ///
  /// The remote parameter, if true, looks up the device key by the
  /// destination address in the key database to encrypt the message.
  /// If remote is true, but requested key does not exist, a NotFound
  /// error will be returned. If set to false, the local node's
  /// device key is used.
  ///
  /// The net_index parameter is the subnet index of the network on
  /// which the message is to be sent.
  ///
  /// The options parameter is a dictionary with the following keys
  /// defined:
  ///
  ///     bool ForceSegmented
  ///         Specifies whether to force sending of a short
  ///         message as one-segment payload. If not present,
  ///         the default setting is "false".
  ///
  /// The data parameter is an outgoing message to be encrypted by the
  /// meshd daemon and sent on.
  ///
  /// Possible errors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotFound
  ///
  fn dev_key_send(&self, element_path: &zbus::zvariant::ObjectPath<'_>, destination: u16, remote: bool, net_index: u16, options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>, data: &[u8]) -> zbus::Result<()>;

  /// This method is used to send add or update network key originated
  /// by the local configuration client to a remote configuration
  /// server.
  ///
  /// The element_path parameter is the object path of an element from
  /// a collection of the application elements (see Mesh Application
  /// Hierarchy section).
  ///
  /// The destination parameter contains the destination address. This
  /// destination must be a uint16 to a nodes primary unicast address.
  ///
  /// The subnet_index parameter refers to the subnet index of the
  /// network that is being added or updated. This key must exist in
  /// the local key database.
  ///
  /// The net_index parameter is the subnet index of the network on
  /// which the message is to be sent.
  ///
  /// The update parameter indicates if this is an addition or an
  /// update. If true, the subnet key must be in the phase 1 state of
  /// the key update procedure.
  ///
  /// Possible errors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotFound
  ///
  fn add_net_key(&self, element_path: &zbus::zvariant::ObjectPath<'_>, destination: u16, subnet_index: u16, net_index: u16, update: bool) -> zbus::Result<()>;

  /// This method is used to send add or update network key originated
  /// by the local configuration client to a remote configuration
  /// server.
  ///
  /// The element_path parameter is the object path of an element from
  /// a collection of the application elements (see Mesh Application
  /// Hierarchy section).
  ///
  /// The destination parameter contains the destination address. This
  /// destination must be a uint16 to a nodes primary unicast address.
  ///
  /// The app_index parameter refers to the application key which is
  /// being added or updated. This key must exist in the local key
  /// database.
  ///
  /// The net_index parameter is the subnet index of the network on
  /// which the message is to be sent.
  ///
  /// The update parameter indicates if this is an addition or an
  /// update. If true, the subnet key must be in the phase 1 state of
  /// the key update procedure.
  ///
  /// Possible errors:
  ///     org.bluez.mesh.Error.InvalidArguments
  ///     org.bluez.mesh.Error.NotFound
  ///
  fn add_app_key(&self, element_path: &zbus::zvariant::ObjectPath<'_>, destination: u16, app_index: u16, net_index: u16, update: bool) -> zbus::Result<()>;

  /// This method is used to send a publication originated by a local
  /// model. If the model does not exist, or it has no publication
  /// record, the method returns org.bluez.mesh.Error.DoesNotExist
  /// error.
  ///
  /// The element_path parameter is the object path of an element from
  /// a collection of the application elements (see Mesh Application
  /// Hierarchy section).
  ///
  /// The model parameter contains a model ID, as defined by the
  /// Bluetooth SIG. If the options dictionary contains a "Vendor"
  /// key, then this ID is defined by the specified vendor.
  ///
  /// The options parameter is a dictionary with the following keys
  /// defined:
  ///
  ///     bool ForceSegmented
  ///         Specifies whether to force sending of a short
  ///         message as one-segment payload. If not present,
  ///         the default setting is "false".
  ///
  ///     uint16 Vendor
  ///         A 16-bit Company ID as defined by the
  ///         Bluetooth SIG. This key should only exist when
  ///         publishing on a Vendor defined model.
  ///
  /// The data parameter is an outgoing message to be encrypted by the
  /// meshd daemon and sent on.
  ///
  /// Since only one Publish record may exist per element-model, the
  /// destination and key_index are obtained from the Publication
  /// record cached by the daemon.
  ///
  /// Possible errors:
  ///     org.bluez.mesh.Error.DoesNotExist
  ///     org.bluez.mesh.Error.InvalidArguments
  ///
  fn publish(&self, element_path: &zbus::zvariant::ObjectPath<'_>, model: u16, options: &std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>, data: &[u8]) -> zbus::Result<()>;

  /// The dictionary that contains information about feature support.
  /// The following keys are defined:
  ///
  /// boolean Friend
  ///
  ///     Indicates the ability to establish a friendship with a
  ///     Low Power node
  ///
  /// boolean LowPower
  ///
  ///     Indicates support for operating in Low Power node mode
  ///
  /// boolean Proxy
  ///
  ///     Indicates support for GATT proxy
  ///
  /// boolean Relay
  ///     Indicates support for relaying messages
  ///
  /// If a key is absent from the dictionary, the feature is not supported.
  /// Otherwise, true means that the feature is enabled and false means that
  /// the feature is disabled.
  ///
  #[zbus(property)]
  fn features(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

  /// This property indicates whether the periodic beaconing is
  /// enabled (true) or disabled (false).
  ///
  #[zbus(property)]
  fn beacon(&self) -> zbus::Result<bool>;

  /// When true, indicates that the network is in the middle of IV
  /// Index Update procedure. This information is only useful for
  /// provisioning.
  ///
  #[zbus(property)]
  fn iv_update(&self) -> zbus::Result<bool>;

  /// This property may be read at any time to determine the IV_Index
  /// that the current network is on. This information is only useful
  /// for provisioning.
  ///
  #[zbus(property)]
  fn iv_index(&self) -> zbus::Result<u32>;

  /// This property may be read at any time to determine the number of
  /// seconds since mesh network layer traffic was last detected on
  /// this node's network.
  ///
  #[zbus(property)]
  fn seconds_since_last_heard(&self) -> zbus::Result<u32>;

  /// This property contains unicast addresses of node's elements.
  ///
  #[zbus(property)]
  fn addresses(&self) -> zbus::Result<Vec<u16>>;

  /// This property may be read at any time to determine the
  /// sequence number.
  ///
  #[zbus(property)]
  fn sequence_number(&self) -> zbus::Result<u32>;
}
