//! # D-Bus interface proxy for: `org.bluez.mesh.Provisioner1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.mesh.Provisioner1", default_service = "org.bluez")]
pub trait Provisioner1 {
}
