//! # D-Bus interface proxy for: `org.bluez.mesh.ProvisionAgent1`
//!
//! This code was generated by `bluez_zbus_generator.py` from BlueZ documentation.

use zbus::proxy;

#[proxy(interface = "org.bluez.mesh.ProvisionAgent1", default_service = "org.bluez")]
pub trait ProvisionAgent1 {

  /// This method is called during provisioning if the Provisioner
  /// has requested Out-Of-Band ECC key exchange. The Private key is
  /// returned to the Daemon, and the Public Key is delivered to the
  /// remote Provisioner using a method that does not involve the
  /// Bluetooth Mesh system. The Private Key returned must be 32
  /// octets in size, or the Provisioning procedure will fail and be
  /// canceled.
  ///
  /// This function will only be called if the Provisioner has
  /// requested pre-determined keys to be exchanged Out-of-Band, and
  /// the local role is Unprovisioned device.
  ///
  fn private_key(&self) -> zbus::Result<Vec<u8>>;

  /// This method is called during provisioning if the local device is
  /// the Provisioner, and is requestng Out-Of-Band ECC key exchange.
  /// The Public key is returned to the Daemon that is the matched
  /// pair of the Private key of the remote device. The Public Key
  /// returned must be 64 octets in size, or the Provisioning
  /// procedure will fail and be canceled.
  ///
  /// This function will only be called if the Provisioner has
  /// requested pre-determined keys to be exchanged Out-of-Band, and
  /// the local role is Provisioner.
  ///
  fn public_key(&self) -> zbus::Result<Vec<u8>>;

  /// This method is called when the Daemon has something important
  /// for the Agent to Display, but does not require any additional
  /// input locally. For instance: "Enter "ABCDE" on remote device".
  ///
  fn display_string(&self, value: &str) -> zbus::Result<()>;

  /// This method is called when the Daemon has something important
  /// for the Agent to Display, but does not require any additional
  /// input locally. For instance: "Enter 14939264 on remote device".
  ///
  /// The type parameter indicates the display method. Allowed values
  /// are:
  ///     "blink" - Locally blink LED
  ///     "beep" - Locally make a noise
  ///     "vibrate" - Locally vibrate
  ///     "out-numeric" - Display value to enter remotely
  ///     "push" - Request pushes on remote button
  ///     "twist" - Request twists on remote knob
  ///
  /// The number parameter is the specific value represented by the
  /// Prompt.
  ///
  fn display_numeric(&self, type_: &str, number: u32) -> zbus::Result<()>;

  /// This method is called when the Daemon requests the user to
  /// enter a decimal value between 1-99999999.
  ///
  /// The type parameter indicates the input method. Allowed values
  /// are:
  ///     "blink" - Enter times remote LED blinked
  ///     "beep" - Enter times remote device beeped
  ///     "vibrate" - Enter times remote device vibrated
  ///     "in-numeric" - Enter remotely displayed value
  ///     "push" - Push local button remotely requested times
  ///     "twist" - Twist local knob remotely requested times
  ///
  /// This agent should prompt the user for specific input. For
  /// instance: "Enter value being displayed by remote device".
  ///
  fn prompt_numeric(&self, type_: &str) -> zbus::Result<u32>;

  /// This method is called when the Daemon requires a 16 octet byte
  /// array, as an Out-of-Band authentication.
  ///
  /// The type parameter indicates the input method. Allowed values
  /// are:
  ///     "static-oob" - return 16 octet array
  ///     "in-alpha" - return 16 octet alpha array
  ///
  /// The Static data returned must be 16 octets in size, or the
  /// Provisioning procedure will fail and be canceled. If input type
  /// is "in-alpha", the printable characters should be
  /// left-justified, with trailing 0x00 octets filling the remaining
  /// bytes.
  ///
  fn prompt_static(&self, type_: &str) -> zbus::Result<Vec<u8>>;

  /// This method gets called by the daemon to cancel any existing
  /// Agent Requests. When called, any pending user input should be
  /// canceled, and any display requests removed.
  ///
  fn cancel(&self) -> zbus::Result<()>;

  /// An array of strings with the following allowed values:
  ///     "blink"
  ///     "beep"
  ///     "vibrate"
  ///     "out-numeric"
  ///     "out-alpha"
  ///     "push"
  ///     "twist"
  ///     "in-numeric"
  ///     "in-alpha"
  ///     "static-oob"
  ///     "public-oob"
  ///
  #[zbus(property)]
  fn capabilities(&self) -> zbus::Result<Vec<String>>;

  /// Indicates availability of OOB data. An array of strings with the
  /// following allowed values:
  ///     "other"
  ///     "uri"
  ///     "machine-code-2d"
  ///     "bar-code"
  ///     "nfc"
  ///     "number"
  ///     "string"
  ///     "on-box"
  ///     "in-box"
  ///     "on-paper",
  ///     "in-manual"
  ///     "on-device"
  ///
  #[zbus(property)]
  fn out_of_band_info(&self) -> zbus::Result<Vec<String>>;

  /// Uniform Resource Identifier points to out-of-band (OOB)
  /// information (e.g., a public key)
  #[zbus(property)]
  fn uri(&self) -> zbus::Result<String>;
}
